{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk.graphlib",
    "module": "syncing-core-neoforge",
    "version": "2.0.0-alpha.16+1.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kneelawk.graphlib",
          "module": "core-neoforge",
          "version": {
            "requires": "2.0.0-alpha.16+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6.jar",
          "url": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6.jar",
          "size": 438114,
          "sha512": "39e03a95146d831dfc2be7c11a0947a22f355a50df2216a0df771f712393512a09054ae55d24ef0b3c96d4f8058f1ba20b8eec393fd99c6b1683f7956418725f",
          "sha256": "8f462f3faa80481b77d80198a87950cf4731c6c143cecf9f3553e27bcec98e1a",
          "sha1": "d46c83925b3941455789546ec3d127e0304731f2",
          "md5": "3822d7b52b00070801105b057b475374"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kneelawk.graphlib",
          "module": "core-neoforge",
          "version": {
            "requires": "2.0.0-alpha.16+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6.jar",
          "url": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6.jar",
          "size": 438114,
          "sha512": "39e03a95146d831dfc2be7c11a0947a22f355a50df2216a0df771f712393512a09054ae55d24ef0b3c96d4f8058f1ba20b8eec393fd99c6b1683f7956418725f",
          "sha256": "8f462f3faa80481b77d80198a87950cf4731c6c143cecf9f3553e27bcec98e1a",
          "sha1": "d46c83925b3941455789546ec3d127e0304731f2",
          "md5": "3822d7b52b00070801105b057b475374"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6-sources.jar",
          "url": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6-sources.jar",
          "size": 46724,
          "sha512": "24bf7f29d30d9d0e8f187613162ffce3b0e8719fde8e73ac2de01fde870d1caa16cbcdd1167c45a66afa8236f5ebb63558d845525114d5b6d75223d9fbf496ae",
          "sha256": "a203c42788488c2b073845eac4ac0f1db8f6db1eddd2452f96929b8908b42b62",
          "sha1": "8af9a2248fa90d7deacb0516828983b169cb2e3c",
          "md5": "484924d7fb83a76c32ec6b768d62d00d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6-javadoc.jar",
          "url": "syncing-core-neoforge-2.0.0-alpha.16+1.20.6-javadoc.jar",
          "size": 111432,
          "sha512": "2c5bbe6c3bb335c6d1c0d74b7b7dae8dcbfc1215e7656e0ee2e0f6bc33715a68b4e2676903aa535a7424dbe3154bb00b06590fe745ff170272c5af57cb336079",
          "sha256": "d23e8684c78713236e216fa6b2446e26b296677e5cea501e47e5547efd27b015",
          "sha1": "58f71c811d7ea0bfe3d0b1c7713e56008af0e9a8",
          "md5": "7e963246ee2c44f438f4acffb87474ac"
        }
      ]
    }
  ]
}
