{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk.graphlib",
    "module": "core-fabric",
    "version": "2.0.0-alpha.5+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-fabric-2.0.0-alpha.5+1.20.4.jar",
          "url": "core-fabric-2.0.0-alpha.5+1.20.4.jar",
          "size": 292570,
          "sha512": "4ae2d2c5bb1f479811070c7b2c490ccb676a9adee2c2a80b1a682ebbe34cbe12e8dcbcdc018a305bd330389c5f35928923071e23327db66afc39d50ede506461",
          "sha256": "759726a3bf0e7896d69812a480494ac1099458031ef8530ce337708bba46a4fa",
          "sha1": "b38eb52272562c1d61d3a383e326d77be80e9ae5",
          "md5": "7124a33c6cbb3fa90e902091c9a8f376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-fabric-2.0.0-alpha.5+1.20.4.jar",
          "url": "core-fabric-2.0.0-alpha.5+1.20.4.jar",
          "size": 292570,
          "sha512": "4ae2d2c5bb1f479811070c7b2c490ccb676a9adee2c2a80b1a682ebbe34cbe12e8dcbcdc018a305bd330389c5f35928923071e23327db66afc39d50ede506461",
          "sha256": "759726a3bf0e7896d69812a480494ac1099458031ef8530ce337708bba46a4fa",
          "sha1": "b38eb52272562c1d61d3a383e326d77be80e9ae5",
          "md5": "7124a33c6cbb3fa90e902091c9a8f376"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-fabric-2.0.0-alpha.5+1.20.4-dev-shadow.jar",
          "url": "core-fabric-2.0.0-alpha.5+1.20.4-dev-shadow.jar",
          "size": 289829,
          "sha512": "7c16abf759864428f6f6adf0570948cf53f619388404385263a0b85c00f03ba3c05042f726d9061e82fc6f9350c5b3f62b04e60f460b359712b2ac95e2fbeb35",
          "sha256": "6bb66b321e0a14b321f23443b15919bf38c54ea8577af59f5c5c21ef3eac12f7",
          "sha1": "4581d21126b4011bbd4e48487909100a1017b648",
          "md5": "e72edfe00bbeeeee5354e29581523156"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-fabric-2.0.0-alpha.5+1.20.4-javadoc.jar",
          "url": "core-fabric-2.0.0-alpha.5+1.20.4-javadoc.jar",
          "size": 377912,
          "sha512": "dabbe653c9d4d9139de1ef3dbe9eb98ed22bdf9a00761cf88cbca2b28eafe2b55a52ae622332757a6fc20b95b6b6d8587ac5615e9f2f806c8e733b2ca4096468",
          "sha256": "bcb19b7c34b080dbfb00511690fa632c7310328d092b9ec5add7faa252b4a12d",
          "sha1": "f195d0bbaef03b615a1b9432914046feaf883487",
          "md5": "b8e19ea622ac943c68086bb71b4db561"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-fabric-2.0.0-alpha.5+1.20.4-sources.jar",
          "url": "core-fabric-2.0.0-alpha.5+1.20.4-sources.jar",
          "size": 230917,
          "sha512": "11c0c23020a84af5c7823b9168393404de088cb2ed83fd959c78c7ddc5fe79fcd2950a496eee2ea5773a6d64f7d79bdc8d08f7945a96cf9bfd1764b70fe2f936",
          "sha256": "a7491a16d2a5e13443466e0b770beee24af861e80cb1e20aa48f8acbc1ea4bdd",
          "sha1": "0e252f86d4a498585f3ee5e5096617d44edea4bd",
          "md5": "e86422fc314c6776aaebe93bc90998e8"
        }
      ]
    }
  ]
}
