{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.37+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.37+1.20.jar",
          "url": "graphlib-1.0.0-alpha.37+1.20.jar",
          "size": 312632,
          "sha512": "1bfef6827ad49e1b65c8b7d60016d1936b914dc42cf35a0c11372478ee2ba004e9841c3f2452caacb6650873fe7774faefd4d532f563e4d9bc7ed6e454b24dd2",
          "sha256": "f8cc2e7fa50b9beed444be2f7f794eaa5e11a3c57aff000126ae289b2bb37a0b",
          "sha1": "006e2d39a8b8e738a35be9ed3322d1ae56c72f65",
          "md5": "893ca1448e5ea875d3a82a73c7fff269"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.37+1.20.jar",
          "url": "graphlib-1.0.0-alpha.37+1.20.jar",
          "size": 312632,
          "sha512": "1bfef6827ad49e1b65c8b7d60016d1936b914dc42cf35a0c11372478ee2ba004e9841c3f2452caacb6650873fe7774faefd4d532f563e4d9bc7ed6e454b24dd2",
          "sha256": "f8cc2e7fa50b9beed444be2f7f794eaa5e11a3c57aff000126ae289b2bb37a0b",
          "sha1": "006e2d39a8b8e738a35be9ed3322d1ae56c72f65",
          "md5": "893ca1448e5ea875d3a82a73c7fff269"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.37+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.37+1.20-javadoc.jar",
          "size": 396144,
          "sha512": "7b9dfb6216fc9dc61e9e7a08a63e5e7994e10a5f7470ae0b201efaa6364bdd3e9ea0f87a9a57fcfe07643f188f98831c0dda63b287c82dc5e78a382cb37a9e25",
          "sha256": "f6e6e9ccebd0908544ee1bfe411926a7f31a500a3f17bc8eda2586b6e43bc712",
          "sha1": "a92dc22fff30ba40ade770e7dbd7fa85dc790fe1",
          "md5": "b8d18a4d7bcfad0860666ba8b3a1fcb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.37+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.37+1.20-sources.jar",
          "size": 225899,
          "sha512": "ef8408c3ad3c0ebdb0be1a4ae31bcea41bb80335d2823b3882c84198bc37df7d04d2d1bfc9c15cbe9948f15d2b52bfa6fd820dc4753ab47b2c74b8f9d8f6a21e",
          "sha256": "350aaacba43efbee9dd6a73512fd3b8da08157fc84240f6fd3aaf692d70ea3b1",
          "sha1": "44892ed283c35aee72d3f2216590643deadb5cfb",
          "md5": "6b84e181aa80b05a2969bb0f83723230"
        }
      ]
    }
  ]
}
