{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.18+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.18+1.20.jar",
          "url": "graphlib-1.0.0-alpha.18+1.20.jar",
          "size": 271724,
          "sha512": "ea784dd10d445bc4276baad68c43623671f689156ec29a0ed258b5a40ccfc2674e5dbc0d37ce9034fedb2571a32ec368cdbbf5e2abf5ee31fa542a50c5d5f022",
          "sha256": "a39c075bc3b218f143546959a92675b63dca32c7c255f225faa4c1bd984ec524",
          "sha1": "a99f85d275cd4ea30fe3e060584bb916201aee38",
          "md5": "a12f20c58c4a0c9ba98dbd9768bd99b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.18+1.20.jar",
          "url": "graphlib-1.0.0-alpha.18+1.20.jar",
          "size": 271724,
          "sha512": "ea784dd10d445bc4276baad68c43623671f689156ec29a0ed258b5a40ccfc2674e5dbc0d37ce9034fedb2571a32ec368cdbbf5e2abf5ee31fa542a50c5d5f022",
          "sha256": "a39c075bc3b218f143546959a92675b63dca32c7c255f225faa4c1bd984ec524",
          "sha1": "a99f85d275cd4ea30fe3e060584bb916201aee38",
          "md5": "a12f20c58c4a0c9ba98dbd9768bd99b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.18+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.18+1.20-javadoc.jar",
          "size": 313174,
          "sha512": "de5c2e0e851b8389e0d2b3a49e963294c87aaed48f79579fec310c2a687a8636fdf58bf1860d7d1d593bd430fd30939a8ea52f4a9cb66275351b245b6b8944c9",
          "sha256": "4e820d95d8263c1ea441afa1f8cb7da80dba98c2f283f07361a5cef9edbc62fa",
          "sha1": "4ff46218a29ba43c451b02a0a990c3b86355d223",
          "md5": "4303d0484633237f0112d22d3161c70a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.18+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.18+1.20-sources.jar",
          "size": 196613,
          "sha512": "520c02630e346963e7e40a3076a07caa425cf58f68830f3b250a96540973b3e49f49cb32c3267a131f9eaf452c47399636d18a40fe2ba67bfdcaf8da53d7c6a4",
          "sha256": "5691fa14d8a207bb6f5b747361a5f413311016056436cf91bad7e58f049d1417",
          "sha1": "ede5e9a949eb8af819506aff458e7e094ff70bcf",
          "md5": "892e4d12104ff07209a57d50af0aa750"
        }
      ]
    }
  ]
}
