{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.36+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.36+1.20.jar",
          "url": "graphlib-1.0.0-alpha.36+1.20.jar",
          "size": 311592,
          "sha512": "651648a0b6100e2bddf41b39b2003934c71c43ba2f5527cb7d432dc9d449571c1e6a913d2a0b596ffe25cd694b586ead2e186dcf85d83944c67ee718c322c7f0",
          "sha256": "f6f7d67a96a618bb0ac5ddf3325d29f66690cb58b1e38c674c2f95f38962f8b3",
          "sha1": "d94c77729aaddaa51798414da7bab5b8d7db5697",
          "md5": "e454a08dba404e436aa4363d4c4ca962"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.36+1.20.jar",
          "url": "graphlib-1.0.0-alpha.36+1.20.jar",
          "size": 311592,
          "sha512": "651648a0b6100e2bddf41b39b2003934c71c43ba2f5527cb7d432dc9d449571c1e6a913d2a0b596ffe25cd694b586ead2e186dcf85d83944c67ee718c322c7f0",
          "sha256": "f6f7d67a96a618bb0ac5ddf3325d29f66690cb58b1e38c674c2f95f38962f8b3",
          "sha1": "d94c77729aaddaa51798414da7bab5b8d7db5697",
          "md5": "e454a08dba404e436aa4363d4c4ca962"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.36+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.36+1.20-javadoc.jar",
          "size": 393230,
          "sha512": "a1614392d7dcb2538899786c9470f2909bf3a3a85514213ebef50c2f5af35e5bb69ea71bb4d268eb87a2ed8e82a00b875f76408dc0c356406242bd67b1ff9a80",
          "sha256": "9d3f0bfe19765d74b61150a1d5bdd956dff13054e62a8464026826bbd81b2c34",
          "sha1": "119c73ac36a021628feabb0e99783d06a36f9fed",
          "md5": "a832b6e7c6db0411c132f79d3fcfe5fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.36+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.36+1.20-sources.jar",
          "size": 224926,
          "sha512": "6b1f76d1e9b931f235a0964fbd0433b7743038f492dd6c5ad3b76867de1b0ed87931c31c325222723893cd35f92b1fe8e0137a35224d54f4725517d958cdc37f",
          "sha256": "184f3fd324e15bf6b12c2ba84fcd511dc88bd3ce9c7d42298df7723b7de4662e",
          "sha1": "5a10d5c80925a65e11d02b203f8233a6fc006ef4",
          "md5": "1ff714ba724fe5c9a58c96feb529b0ab"
        }
      ]
    }
  ]
}
