{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-rendertag",
    "version": "0.2.1+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.1+1.20.jar",
          "url": "kmodlib-rendertag-0.2.1+1.20.jar",
          "size": 20472,
          "sha512": "6caff185e966b5eabe6a2135984d957a3d62bd14e7f97b836a1803510aa5a58f2ba4d11d36f1f263ea834d805acfa6ba2a677ce0c2afdd61aee4ee4d040ece12",
          "sha256": "07625635abde05bab57cee28c54b7063f89ab7d8229b4234de39e37a9ef7bf75",
          "sha1": "80a24d6b42bad9bdedceeeb10339df4bc90b06a4",
          "md5": "5ca0c11b59d165b3401b76f37074b382"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.1+1.20.jar",
          "url": "kmodlib-rendertag-0.2.1+1.20.jar",
          "size": 20472,
          "sha512": "6caff185e966b5eabe6a2135984d957a3d62bd14e7f97b836a1803510aa5a58f2ba4d11d36f1f263ea834d805acfa6ba2a677ce0c2afdd61aee4ee4d040ece12",
          "sha256": "07625635abde05bab57cee28c54b7063f89ab7d8229b4234de39e37a9ef7bf75",
          "sha1": "80a24d6b42bad9bdedceeeb10339df4bc90b06a4",
          "md5": "5ca0c11b59d165b3401b76f37074b382"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.1+1.20-javadoc.jar",
          "url": "kmodlib-rendertag-0.2.1+1.20-javadoc.jar",
          "size": 99202,
          "sha512": "3edffa43b302f7175508b312be420e91928616031aa4e2bcde58aa052070731dc3f685c79037fd21a04e04f2f512d44f8cbe9826c01ca1e5fb386f250860ca7d",
          "sha256": "c0776822404469917f603884a3889b8c9f524841a380dfab890672496bea5edc",
          "sha1": "f15b3a5cdb0870acf93bfb684cdf104017143fb5",
          "md5": "20dd039162e07bf24ddb386c30052805"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.1+1.20-sources.jar",
          "url": "kmodlib-rendertag-0.2.1+1.20-sources.jar",
          "size": 14382,
          "sha512": "06dc5fd17f653ab615ad948b305b1fa946f189a054bf7b5081a3838641b2480bc9c392d8e64b5c47544497213b1cb5a67a0a9ca2fe3e8423672165608e33aee7",
          "sha256": "e3feb4eebc06a3349acc4fd961382cd0234f38667f50e1ce734d9a45a05be8ac",
          "sha1": "acbe9dccfdb93c22608307163665dc6f4db7d051",
          "md5": "232831d09c25cc519be15876b6ac7657"
        }
      ]
    }
  ]
}
