{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.40+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.10.0-pre.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "net.fabricmd.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.40+1.20.jar",
          "url": "graphlib-1.0.0-alpha.40+1.20.jar",
          "size": 541407,
          "sha512": "c17068fa2518a5f6ce7d0d808b83d7d676090738197332debbfac3614b6f0a78c812424f8708eccce269cdbc7de71110db1117dc4e174a223bd97b7ebc762cb1",
          "sha256": "9786baed54f6e99db121a0458ac9d359fc5235a2c2992be5320da5c81ea2b011",
          "sha1": "1e57c4fde148ee2a1c5197d03308a2930728038a",
          "md5": "a49ead063930badaabc4dfbd247160c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.10.0-pre.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "net.fabricmd.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.40+1.20.jar",
          "url": "graphlib-1.0.0-alpha.40+1.20.jar",
          "size": 541407,
          "sha512": "c17068fa2518a5f6ce7d0d808b83d7d676090738197332debbfac3614b6f0a78c812424f8708eccce269cdbc7de71110db1117dc4e174a223bd97b7ebc762cb1",
          "sha256": "9786baed54f6e99db121a0458ac9d359fc5235a2c2992be5320da5c81ea2b011",
          "sha1": "1e57c4fde148ee2a1c5197d03308a2930728038a",
          "md5": "a49ead063930badaabc4dfbd247160c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.40+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.40+1.20-javadoc.jar",
          "size": 446595,
          "sha512": "d33e541f625f4b78352f4b4b3e19fb38bc71a3c13199af87586d65b6cf5c0f487659aea46d1cfe1b31cbe8b900f2b5bb83936561f37865460f572d097f17c405",
          "sha256": "fa150593eed67115c5ededc3a3b751327a41cc1e82c7dbcc5cf0c85aec4c97fe",
          "sha1": "26b40c9d3454b55137313b00d8df24055baa0635",
          "md5": "7dd446d90d86daaec17ac50e73e48574"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.40+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.40+1.20-sources.jar",
          "size": 284499,
          "sha512": "9f6504af0325f4b7fa8dc5a4b99d129a34dd8c9bd32041fe5f4e6ced2b191f9f3dd7025f5d2a0e1b649fc1fb75e2e2619a3ba67a71ab2e752be09c0e57afd0df",
          "sha256": "9138a23d9237235f81418284376bbe9958d907bf22347be7201aad950c7f814b",
          "sha1": "c303213a3f5dd6b8e5178ea9970b2a4c7dc49364",
          "md5": "d140ad588134a269a69d30ec80471150"
        }
      ]
    }
  ]
}
