{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-renderlayer",
    "version": "0.2.4+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-renderlayer-0.2.4+1.20.jar",
          "url": "kmodlib-renderlayer-0.2.4+1.20.jar",
          "size": 10598,
          "sha512": "854daa588284ba5acbb66f0ec5802ba3a05cf7cace349bd197407aa550c2db9aec9ba485e9b9081ca8aa999904d624d23cae43a815b246ad7b19d7bf44e7a893",
          "sha256": "28cb937a37b1e07c7d074fe231579812ec6bedbf9ec17fc5ad9dd97675d1c8b5",
          "sha1": "b10dfa1bbfc077d35aa2110fd950bd4f3f16a537",
          "md5": "2bab24d82f4d190e275f3d986bdb0432"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-renderlayer-0.2.4+1.20.jar",
          "url": "kmodlib-renderlayer-0.2.4+1.20.jar",
          "size": 10598,
          "sha512": "854daa588284ba5acbb66f0ec5802ba3a05cf7cace349bd197407aa550c2db9aec9ba485e9b9081ca8aa999904d624d23cae43a815b246ad7b19d7bf44e7a893",
          "sha256": "28cb937a37b1e07c7d074fe231579812ec6bedbf9ec17fc5ad9dd97675d1c8b5",
          "sha1": "b10dfa1bbfc077d35aa2110fd950bd4f3f16a537",
          "md5": "2bab24d82f4d190e275f3d986bdb0432"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-renderlayer-0.2.4+1.20-javadoc.jar",
          "url": "kmodlib-renderlayer-0.2.4+1.20-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-renderlayer-0.2.4+1.20-sources.jar",
          "url": "kmodlib-renderlayer-0.2.4+1.20-sources.jar",
          "size": 9821,
          "sha512": "3ae8b7aade3fd83c77b00e9d2018e96f175569f50f9b25b39d21005ca0b8bd02d4511bf48e3a1d924180dc14b590a928b0bd06769084f08e569208509da99f3e",
          "sha256": "d2f027bd402a929282e5f5aa31fa880a90be936b29d0037fb1f68a249c0f5964",
          "sha1": "9a4008141f1990c7178689e550aa46c98d98f093",
          "md5": "14112a990f1816cca10504a443be4401"
        }
      ]
    }
  ]
}
