{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.14+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.14+1.20.jar",
          "url": "graphlib-1.0.0-alpha.14+1.20.jar",
          "size": 278963,
          "sha512": "bbc0bff3cb4bc84ee76efcf16dda494904498ee575ed09e5feb80b42cf37c02e8c64f2b23b6e99bdd8cff26019627a43301dc170d9153ea04f0cff9b542758de",
          "sha256": "aace86b127da9eeb5e1bfa59e5201fb746b595fee91e504b7c5ab3d5c41f639b",
          "sha1": "c1248b6bd5f6b09bffdc9de330ab6c7c5d68ca0a",
          "md5": "a4b1ed122b3a0fa8345180a0459d925c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.14+1.20.jar",
          "url": "graphlib-1.0.0-alpha.14+1.20.jar",
          "size": 278963,
          "sha512": "bbc0bff3cb4bc84ee76efcf16dda494904498ee575ed09e5feb80b42cf37c02e8c64f2b23b6e99bdd8cff26019627a43301dc170d9153ea04f0cff9b542758de",
          "sha256": "aace86b127da9eeb5e1bfa59e5201fb746b595fee91e504b7c5ab3d5c41f639b",
          "sha1": "c1248b6bd5f6b09bffdc9de330ab6c7c5d68ca0a",
          "md5": "a4b1ed122b3a0fa8345180a0459d925c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.14+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.14+1.20-javadoc.jar",
          "size": 331467,
          "sha512": "bf972f9cf8cb15abe818b2724a01b703ef215f608d52938f7c3bc2165e61c817861dec3e2160680b215f769217e3b4786fea1e47dff444d6214ae2a26d64a464",
          "sha256": "9a10f3d8cda4d30771004cca7166b696956135cfaee213a0ed8d106a0d1ad29e",
          "sha1": "c3b22f0852c9a90700bbff350b50f96c64b93a3d",
          "md5": "6f9d751c5fef43f18edd6424551f3887"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.14+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.14+1.20-sources.jar",
          "size": 201001,
          "sha512": "739a5501e46ea33d9ba2337fc12359d3331df692dd0fe68afc98333bd44a3ae5126f16a7ae6aeb9fcba7c72a73a939dfb88e6a84b3daa21855e5f6255ff5f1eb",
          "sha256": "6334f823291452b792aa7eb6976255fd095f587c26d444f9e197354733d8dc58",
          "sha1": "865e89220d1c9321111b5229b11942f384625c05",
          "md5": "c11d3dc3ab5481ec8c8c5353d44ae91e"
        }
      ]
    }
  ]
}
