{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "wired-redstone",
    "version": "0.4.18+1.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.4.18+1.19.2.jar",
          "url": "wired-redstone-0.4.18+1.19.2.jar",
          "size": 2944506,
          "sha512": "84d6245d146c6780a9f602caab41a3e67b090ab8fca46feb6ccb7b147d2a7731d0161da296d4cfd7b3d9967ee6e713098e066225064d7447fb387ad39d4f8fcd",
          "sha256": "1880a96be90d64a5f477c1b373230b391ea44719857fec85fa0ce00be0c6d63b",
          "sha1": "4b5af509ac582b67efc0bee49d50573ec58d9b38",
          "md5": "f13207471950667c7c8eb154c167bab8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.8"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-config",
          "version": {
            "requires": "1.0.0-beta.6"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-json5",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.5"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.9.3+kotlin.1.8.20"
          }
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libmultipart-all",
          "version": {
            "requires": "0.8.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.kneelawk",
          "module": "graphlib",
          "version": {
            "requires": "0.3.6+1.19.2"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "lmp-compat",
          "version": {
            "requires": "0.2.3+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.4.18+1.19.2.jar",
          "url": "wired-redstone-0.4.18+1.19.2.jar",
          "size": 2944506,
          "sha512": "84d6245d146c6780a9f602caab41a3e67b090ab8fca46feb6ccb7b147d2a7731d0161da296d4cfd7b3d9967ee6e713098e066225064d7447fb387ad39d4f8fcd",
          "sha256": "1880a96be90d64a5f477c1b373230b391ea44719857fec85fa0ce00be0c6d63b",
          "sha1": "4b5af509ac582b67efc0bee49d50573ec58d9b38",
          "md5": "f13207471950667c7c8eb154c167bab8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.4.18+1.19.2-shadow-dev.jar",
          "url": "wired-redstone-0.4.18+1.19.2-shadow-dev.jar",
          "size": 2153222,
          "sha512": "c3256d5b45d4a9c55be1dfd6c9b9c87d9d1c3cb9bffe3e400c62b19cfa25f341057937d111a01598693f198c8b80f0c25aa333b5f9151b899bd88a9bbda20c5c",
          "sha256": "73b4affae85537e9ab79e4f05bfcb6e8e416cf1f72eab6fba203237f74ed2eff",
          "sha1": "37669cbc6b2e268ee0d00cf1da6f5b164bbff41d",
          "md5": "865d61a9a870d042caad9fc67594f258"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.4.18+1.19.2-sources.jar",
          "url": "wired-redstone-0.4.18+1.19.2-sources.jar",
          "size": 1801609,
          "sha512": "af4c93069d9dc31433cbad71cea98370fd38fa61af6b1a7fcc7ff003de8fb8d49c635e75825604750bc7c42249e5990399da7a2fb12e541778e1101e1e37a8e9",
          "sha256": "e2d7619b4dfdd2c90af07921bdd8514104f9bd851b61547bae474b3ecaab09a0",
          "sha1": "2605abf210c6b62b28f5b0a020cb1f17173ff785",
          "md5": "3a428efcbb33e56525eb6a510fbc0f92"
        }
      ]
    }
  ]
}
