{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-overlay",
    "version": "0.2.8+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.8+1.20.jar",
          "url": "kmodlib-overlay-0.2.8+1.20.jar",
          "size": 15897,
          "sha512": "992c3ea6d0f2b77238d80687172bef1bb05158eb6ef1e9913f96858bd210db0e360f1d5683d3a4577461687fa243dd1e6b3a7e82db89af430b8be3f647d1bd12",
          "sha256": "750c30c26d0967e4e9097f10739bde35479023906b3a6416b9a7fb2311acf573",
          "sha1": "95c025e7a15274bca7a15fcd1bb0bddc5d3a8274",
          "md5": "b5e3514be1e6d3d8093130b4032da567"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.8+1.20.jar",
          "url": "kmodlib-overlay-0.2.8+1.20.jar",
          "size": 15897,
          "sha512": "992c3ea6d0f2b77238d80687172bef1bb05158eb6ef1e9913f96858bd210db0e360f1d5683d3a4577461687fa243dd1e6b3a7e82db89af430b8be3f647d1bd12",
          "sha256": "750c30c26d0967e4e9097f10739bde35479023906b3a6416b9a7fb2311acf573",
          "sha1": "95c025e7a15274bca7a15fcd1bb0bddc5d3a8274",
          "md5": "b5e3514be1e6d3d8093130b4032da567"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.8+1.20-javadoc.jar",
          "url": "kmodlib-overlay-0.2.8+1.20-javadoc.jar",
          "size": 85459,
          "sha512": "87898e33e6184c5fada9f109b7f496576d2d4801a2edb9cbb51ba68c64af2f1803440ef45320fbe419405968f013cf4e5902c94e3116355992acb6ef7e0dab33",
          "sha256": "25c18ccfcac8bdaa0c605ff1a8f5e6f03a6ddda7d02621dc15918bfdeb753357",
          "sha1": "9cdd13c4d7d1b5041c449d4f346300bd37b8c0f6",
          "md5": "5ecc9a8acd45afe85e0a875b8b7fb3d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.8+1.20-sources.jar",
          "url": "kmodlib-overlay-0.2.8+1.20-sources.jar",
          "size": 13022,
          "sha512": "87f172e0a8afff6647c8dbfb34c4e02b47c5ad1a780468afcac723aa83a5932b45e0ebca00c6375aa1adabdaeab4d2666088e78e11833dddc9fee9fa4e351c81",
          "sha256": "c2d6ef54c8256c17588af9d0b16f11b74cb9530a161c9e6c682491be1a2b1664",
          "sha1": "f71a3cf63d608392d66ade60fba65322230c3c01",
          "md5": "99b8ee678cbb1da9ef26861ce7a24512"
        }
      ]
    }
  ]
}
