{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.12+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.12+1.20.jar",
          "url": "graphlib-1.0.0-alpha.12+1.20.jar",
          "size": 278695,
          "sha512": "47ced85993ddfac17b2f497696c2c364e8d31e57aa38f89e125646bd7f32423d39d0c93dd3a2455a213201b4299b8540ae9e0b7d6640adc57cfc5cc2c6d59e20",
          "sha256": "7be4f4a451a5c696b8d92748ec1b9c2ffa6f24e8de987c189739bd822a12867a",
          "sha1": "5bb478341869407eea6dca92c9e01d7626c03c6b",
          "md5": "33fc8a7c07be5393db89352b9e586e1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.12+1.20.jar",
          "url": "graphlib-1.0.0-alpha.12+1.20.jar",
          "size": 278695,
          "sha512": "47ced85993ddfac17b2f497696c2c364e8d31e57aa38f89e125646bd7f32423d39d0c93dd3a2455a213201b4299b8540ae9e0b7d6640adc57cfc5cc2c6d59e20",
          "sha256": "7be4f4a451a5c696b8d92748ec1b9c2ffa6f24e8de987c189739bd822a12867a",
          "sha1": "5bb478341869407eea6dca92c9e01d7626c03c6b",
          "md5": "33fc8a7c07be5393db89352b9e586e1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.12+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.12+1.20-javadoc.jar",
          "size": 331383,
          "sha512": "fd1e79116a214877370061b8298d3da2c89eacaa9330ead5233715e836e61a05d75b116c81e5f8a149b7b5cd9daab4ab49fab545d598244560a3e1a8f8cdd26d",
          "sha256": "cbd4eaf212c81242183a4f5ec51de7322db81a0ddd7f7ed95fa16036c71758ad",
          "sha1": "c8d105e572a90a032ef408c571befe41d1f6e3d0",
          "md5": "505a8acf21796620a97b1e8dcd2c7b1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.12+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.12+1.20-sources.jar",
          "size": 200954,
          "sha512": "fefeddfc82162e7c0d075409723f0ed94f4e54d7db68a55b511e582b2becd459f5a9522f1b84ec1f3cbafe8268703222bdf6bcf4cec99f63026623d16e9bf5ca",
          "sha256": "a57519d7916183ef2420a24230ad71944c502da7d87b8a5abbc11fc2e8f461e8",
          "sha1": "36e89717a855ab5658f169e493e4feba4a833997",
          "md5": "d5d86371daeb5dcae402ff37ea800398"
        }
      ]
    }
  ]
}
