{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk.graphlib",
    "module": "syncing-core-xplat-intermediary",
    "version": "2.0.0-alpha.14+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4.jar",
          "size": 47451,
          "sha512": "1419d2a1540a1eb1c6c61d122a91e3b643af26c6fed7b98738d4ff1ac0f79a22915f6b6517a16f08568a99ad457e1496bdb71def65c29e34591d3b7b56626d83",
          "sha256": "c37adbd41dd9120b74d760c8e6a7709d3220bf5f939b730a7cd22a97b7a17013",
          "sha1": "3d94aa54a533cc2112d33a39a8664238e2d6ab07",
          "md5": "617d30f2f52b9e35620bc298949f5d42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4.jar",
          "size": 47451,
          "sha512": "1419d2a1540a1eb1c6c61d122a91e3b643af26c6fed7b98738d4ff1ac0f79a22915f6b6517a16f08568a99ad457e1496bdb71def65c29e34591d3b7b56626d83",
          "sha256": "c37adbd41dd9120b74d760c8e6a7709d3220bf5f939b730a7cd22a97b7a17013",
          "sha1": "3d94aa54a533cc2112d33a39a8664238e2d6ab07",
          "md5": "617d30f2f52b9e35620bc298949f5d42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4-javadoc.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4-javadoc.jar",
          "size": 100071,
          "sha512": "2814eb81715cdad1f585c36767ee4f4b025afea26b40d4c14c9cf755cd80fc4816e1702fa65c6107c724560f136be15f49e986e3eaea41a0036d80a0a541e03d",
          "sha256": "76f2d66b3128e5e1fc74956f2a7b47da0799e4dbf0b57a6e04d7c230c2c265ec",
          "sha1": "5e797cfaf310affa6a31bc8c82bba60d0d4638b7",
          "md5": "864b1ea8057ef819e30a359b2eb9ba1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4-sources.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.14+1.20.4-sources.jar",
          "size": 42181,
          "sha512": "79e8e09ceef5aa560f5363068b640a38edf95bce7912357a70117f2708cbe98e02cf8d972bbc5babe9c4e9ba26af6132c85fce035b83038418f006f5e694fe83",
          "sha256": "d9c372b3a00d43805e1f432f0d491eb09ba96d2845c5e396be1297c7cf745682",
          "sha1": "0f0f4ee36e800cf3e406b53f82406e904e0549f6",
          "md5": "be8f7e753a67ecfba9f9738ac4cf2d48"
        }
      ]
    }
  ]
}
