{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "wired-redstone",
    "version": "0.3.3+1.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.3.3+1.18.2.jar",
          "url": "wired-redstone-0.3.3+1.18.2.jar",
          "size": 2083827,
          "sha512": "8883e791be881dae4653a23b5eef485694d3da456ddd67ef696fac7f1bd10abbc00212f323d5776280d66fff91f741a41a3799589a01cda780c147f58cbe73e6",
          "sha256": "9798f6502f3a1b7515ee3d8b9a322a33a42a3be40b7503651f6547d7d79da542",
          "sha1": "dbd710372aee9f7b2fd02761cb58eb066814f9a3",
          "md5": "883a8c551b41d944fb7d4af361860005"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.13.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.56.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.7.2+kotlin.1.6.20"
          }
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libmultipart-all",
          "version": {
            "requires": "0.7.3-pre.4"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.kneelawk",
          "module": "graphlib",
          "version": {
            "requires": "0.2.4+1.18.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mcp.mobius.waila",
          "module": "wthit",
          "version": {
            "requires": "fabric-4.10.3"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cc-restitched",
          "version": {
            "requires": "1.100.6"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "6.0.42"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.shedaniel.cloth.api",
          "module": "cloth-utils-v1",
          "version": {
            "requires": "2.0.54"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.emi",
          "module": "emi",
          "version": {
            "requires": "0.1.2+1.18.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.3.3+1.18.2.jar",
          "url": "wired-redstone-0.3.3+1.18.2.jar",
          "size": 2083827,
          "sha512": "8883e791be881dae4653a23b5eef485694d3da456ddd67ef696fac7f1bd10abbc00212f323d5776280d66fff91f741a41a3799589a01cda780c147f58cbe73e6",
          "sha256": "9798f6502f3a1b7515ee3d8b9a322a33a42a3be40b7503651f6547d7d79da542",
          "sha1": "dbd710372aee9f7b2fd02761cb58eb066814f9a3",
          "md5": "883a8c551b41d944fb7d4af361860005"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.3.3+1.18.2-sources.jar",
          "url": "wired-redstone-0.3.3+1.18.2-sources.jar",
          "size": 1565672,
          "sha512": "547e0f13c5357a16e321d9a860cf7faa30b5aa8e8b0d8443f906a350d88c295b671c117790bac78255e2f572d58710a02363948a38f43d57c64190f70763d586",
          "sha256": "fef2f1f1fa1227898bf8b1b7dde032e5c78ba9fefca589dd45a9aef224c27663",
          "sha1": "6fa2a1056d9544176719354b4d55d2426815cc7f",
          "md5": "6ee2f3b5021ed5f696c8ff3afa0c3604"
        }
      ]
    }
  ]
}
