{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.20+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.20+1.20.jar",
          "url": "graphlib-1.0.0-alpha.20+1.20.jar",
          "size": 281664,
          "sha512": "ea78f118e1e1b9458cb59b5128e4a9e5ff2543f5d845ac84260d9130c5b51d0ecfd4b6d685a0917a9f12f8d5aaab5eebf339025497eca2f153cf16a6898b9afc",
          "sha256": "597fd334305e35681fc0a74b1d45cd22e1639cc0784d242c3da658963d8fc381",
          "sha1": "35006ebfeb1e8f4274fcfc2e93d3b88cc6780a10",
          "md5": "f9b11c2c8c942ebeb823a42eb19bd43c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.20+1.20.jar",
          "url": "graphlib-1.0.0-alpha.20+1.20.jar",
          "size": 281664,
          "sha512": "ea78f118e1e1b9458cb59b5128e4a9e5ff2543f5d845ac84260d9130c5b51d0ecfd4b6d685a0917a9f12f8d5aaab5eebf339025497eca2f153cf16a6898b9afc",
          "sha256": "597fd334305e35681fc0a74b1d45cd22e1639cc0784d242c3da658963d8fc381",
          "sha1": "35006ebfeb1e8f4274fcfc2e93d3b88cc6780a10",
          "md5": "f9b11c2c8c942ebeb823a42eb19bd43c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.20+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.20+1.20-javadoc.jar",
          "size": 336798,
          "sha512": "8b732aaa19a8fd0ea4a4fd8a0a3f3ec7d08d44d266faa244c840629f9f0bbfd0ad62a92cb85b051e67eb0bc65bf7d76f4033009ef3a8a870f3b66ce858ee3096",
          "sha256": "cf69629339f397105b7a85704f65c9dbdcf5b780fc5ea8bb12ee3b6b4531e53c",
          "sha1": "6817fd78b52748b2a92f28f3484f4de8b8c358ae",
          "md5": "41ca75a12a0c16ce4f37475bd7cb9215"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.20+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.20+1.20-sources.jar",
          "size": 202897,
          "sha512": "169388de2e1089f3170f7259832695d84a3ed7e3b22c95e16785872637e8a4a8ac9c6e6797e37f232775795cb464a97d4be63471fce6a47b4922852131ea9391",
          "sha256": "3f750c3a7976b85c5ea054302befd9049f7f983878d04fd8ecfa63824fa8407e",
          "sha1": "acd6cc51dbdeae8cdc9b3976aa01746ec1860f3b",
          "md5": "1065c11e75533ea9ce2f8a7b7c59cbc4"
        }
      ]
    }
  ]
}
