{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "lmp-compat",
    "version": "0.1.2+1.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lmp-compat-0.1.2+1.18.2.jar",
          "url": "lmp-compat-0.1.2+1.18.2.jar",
          "size": 7285,
          "sha512": "7ab97ad6052194e154ee5c8d62c1fc249c25e1ea9a76934f0f4eeafd57407ad14851f4467db40f1d2cff68b8b19b8475ee12fb298b51876b7ae9b0bf8cb7440b",
          "sha256": "f8aed065f7bf55c12f5a35ad96806af8752e3dd8cd68e14f9629903a1204c14e",
          "sha1": "605e3d66d963593106c17b04c8603a2e05a9f86f",
          "md5": "b2e9e1361514de55ce2865079fdf5dc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.LlamaLad7",
          "module": "MixinExtras",
          "version": {
            "requires": "0.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libmultipart-all",
          "version": {
            "requires": "0.7.5-pre.0.2+kneelawk"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.67.0+1.18.2"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.18.2",
          "version": {
            "requires": "0.5.0g-799+1.18.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lmp-compat-0.1.2+1.18.2.jar",
          "url": "lmp-compat-0.1.2+1.18.2.jar",
          "size": 7285,
          "sha512": "7ab97ad6052194e154ee5c8d62c1fc249c25e1ea9a76934f0f4eeafd57407ad14851f4467db40f1d2cff68b8b19b8475ee12fb298b51876b7ae9b0bf8cb7440b",
          "sha256": "f8aed065f7bf55c12f5a35ad96806af8752e3dd8cd68e14f9629903a1204c14e",
          "sha1": "605e3d66d963593106c17b04c8603a2e05a9f86f",
          "md5": "b2e9e1361514de55ce2865079fdf5dc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lmp-compat-0.1.2+1.18.2-sources.jar",
          "url": "lmp-compat-0.1.2+1.18.2-sources.jar",
          "size": 4719,
          "sha512": "2c497078b0925f4a9829c681598dc0209c482227c6b56775f862eaf5c33b1296c08306799c73f27ac3fa4d9cd27dfea7352f5297d88e49c8f1771587c8ae4efc",
          "sha256": "d269202e2f71047ff76793faa81e02a1776f8ebbc74ecdf45973435e1f06c98e",
          "sha1": "1b78be716e1429d1d7d3f455bbc432d50a64508b",
          "md5": "de5ebce4b26fea609842a16b8314fa3c"
        }
      ]
    }
  ]
}
