{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.11+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.11+1.20.jar",
          "url": "graphlib-1.0.0-alpha.11+1.20.jar",
          "size": 278477,
          "sha512": "076a373b660fbc1a376fff63c240285cd64a1094d67b7912a59842ad1dd0b5fcfae006fbaad8cad733b801a955b5898ce33e510fe720a9888c6e44a5ebfe2662",
          "sha256": "d57351e35163edb22a19916db92312faa9d149134021c35fe3bcc76ab0a665f4",
          "sha1": "9be53d50bc903477b6ffdc3966e120f93c7cbc85",
          "md5": "7cfc8ccd9a623643cf3895af6de6fb1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.11+1.20.jar",
          "url": "graphlib-1.0.0-alpha.11+1.20.jar",
          "size": 278477,
          "sha512": "076a373b660fbc1a376fff63c240285cd64a1094d67b7912a59842ad1dd0b5fcfae006fbaad8cad733b801a955b5898ce33e510fe720a9888c6e44a5ebfe2662",
          "sha256": "d57351e35163edb22a19916db92312faa9d149134021c35fe3bcc76ab0a665f4",
          "sha1": "9be53d50bc903477b6ffdc3966e120f93c7cbc85",
          "md5": "7cfc8ccd9a623643cf3895af6de6fb1d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.11+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.11+1.20-javadoc.jar",
          "size": 331370,
          "sha512": "b2423b5e1fc74e91b1041a071353b6115796b831d3fd878b76feac50672933cc5d3b44f3c0007b6d71f2b81b11ddf0f2f9bcde5012a2b918b92ee6c337b91eb2",
          "sha256": "7a565bda4d0611ac08c500eedf4c2fa5c5185f115315aca1ac8a05fc16310239",
          "sha1": "cb4f7a2255f347d772e5e6a52f82781f6bd3e1f5",
          "md5": "fd711e4f345c7645a9d2c63499a5fda9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.11+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.11+1.20-sources.jar",
          "size": 200942,
          "sha512": "794e17c08903d82dd2acf1dec39472a6d5b708dce06911ba2549ff8c04d316b291ef558bb5f64bc2f41026c950ac12f121ee6c4023ffdd35a1e128dafa12e046",
          "sha256": "a14ef3ad25ebca5dd1e98901ae0548ff7d1dcff2c6bbc4c9ca210f3746392d7f",
          "sha1": "19291a3aebb4817ac48751c4dee19a8d9f09c509",
          "md5": "ee4e9ada068bcad3050c7823ce5de3eb"
        }
      ]
    }
  ]
}
