{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.31+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.31+1.20.jar",
          "url": "graphlib-1.0.0-alpha.31+1.20.jar",
          "size": 305347,
          "sha512": "1931276dd4591400823c31fb5202f94878b67dc14e1946739859a75858b05c50fc4cb851559c0156d245870876f59b06095964bff835e060bd52e4b625c0e77b",
          "sha256": "25bc8996543aebc5cd9dbca3efb9470aad1313e20bbce1cf09f7945e758dee47",
          "sha1": "612fc513f5a4b665fcf8a9f522aec706446a2693",
          "md5": "441c63635721d348acf91b74f5fde62c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.31+1.20.jar",
          "url": "graphlib-1.0.0-alpha.31+1.20.jar",
          "size": 305347,
          "sha512": "1931276dd4591400823c31fb5202f94878b67dc14e1946739859a75858b05c50fc4cb851559c0156d245870876f59b06095964bff835e060bd52e4b625c0e77b",
          "sha256": "25bc8996543aebc5cd9dbca3efb9470aad1313e20bbce1cf09f7945e758dee47",
          "sha1": "612fc513f5a4b665fcf8a9f522aec706446a2693",
          "md5": "441c63635721d348acf91b74f5fde62c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.31+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.31+1.20-javadoc.jar",
          "size": 385098,
          "sha512": "fb963d7822551b7af7498aafb9c75e8ae09019ebd179674f0cc37c97db12c2719273937ae95903d2c65853c4ebd6fed50a09a92d80b7453075f932be43309b39",
          "sha256": "da91637cb93333f4d2485cf7c2bf9445c5e4f75ee7e9aed992bd4d55657d5f0e",
          "sha1": "434e8e40f53f388a6e7018fba4aba5b230304558",
          "md5": "7069cf9802f03b6c015770a93308a17e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.31+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.31+1.20-sources.jar",
          "size": 219762,
          "sha512": "24adea7f99ca8fb63b2a3c37296149a23570d6f17c9929c1de50b2b36d377b9b27bceb7fd96827cc4849e3a4f537ec7dac88f582de60a7de38d7afe122025e27",
          "sha256": "f081ddfc9140293b2e67a58e640ac5b3006e7154bc66803b448ffa58effe4169",
          "sha1": "f5c832304fd61307bf90543bc1aa6a98916adaa7",
          "md5": "a5a670021422dd3c035626a3ce815cde"
        }
      ]
    }
  ]
}
