{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-rendertag",
    "version": "0.2.2+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.2+1.20.jar",
          "url": "kmodlib-rendertag-0.2.2+1.20.jar",
          "size": 20471,
          "sha512": "07b9abc27a6dced45606bf5393387e6717960bbdc6f8e7e577632204032d7153ca942bfd4170948dbfd0a085b8b25ad02a0cbb3960aa0f4373165446ab1317df",
          "sha256": "b264776084cafcbb3685e942669a5ed0c3a35f488799a18bf715e79c3a60e88d",
          "sha1": "4b057319deb8114369d2d4ed24a23d85137f1415",
          "md5": "bbc060938bb9ff67e0f0d57a634cf761"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.2+1.20.jar",
          "url": "kmodlib-rendertag-0.2.2+1.20.jar",
          "size": 20471,
          "sha512": "07b9abc27a6dced45606bf5393387e6717960bbdc6f8e7e577632204032d7153ca942bfd4170948dbfd0a085b8b25ad02a0cbb3960aa0f4373165446ab1317df",
          "sha256": "b264776084cafcbb3685e942669a5ed0c3a35f488799a18bf715e79c3a60e88d",
          "sha1": "4b057319deb8114369d2d4ed24a23d85137f1415",
          "md5": "bbc060938bb9ff67e0f0d57a634cf761"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.2+1.20-javadoc.jar",
          "url": "kmodlib-rendertag-0.2.2+1.20-javadoc.jar",
          "size": 99202,
          "sha512": "9ce86d824dd4938db63c517739a9cb9488395775eb24f6fe725b6c30a008ee7d61150ddbf24ad369ebc1efb40527d63244c3bb7dfec995ab643bdb83596ecf4c",
          "sha256": "c3deed29692ff7ded00efd5c71b5c12ac3d731463956277670228ee99b7cb8e0",
          "sha1": "f73256f83157916938fff519d14663aac709c93f",
          "md5": "9d36e77b884164f26bc114de049323ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-rendertag-0.2.2+1.20-sources.jar",
          "url": "kmodlib-rendertag-0.2.2+1.20-sources.jar",
          "size": 14381,
          "sha512": "bbde8515c57d273a3084bbd76ec06f9f249a6645c4e5bf411f867129f1416df045f95cf1291edb7ea7afc124bce27fe3b33a11d94a4b5d5c10a8d8963be450e5",
          "sha256": "3a54acd5a7672fab1c409647da6c63ad2141c66d903ca301bf174eb208b8ce03",
          "sha1": "10902af46a558a6a0b143570375dfe02720c9293",
          "md5": "559e84b3e2121382d383379f29634578"
        }
      ]
    }
  ]
}
