{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.10+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.10+1.20.jar",
          "url": "graphlib-1.0.0-alpha.10+1.20.jar",
          "size": 278063,
          "sha512": "edd6b7898dba3aa64b9f3503c26170bf8c6f3459906f9818947456e22e7ad3203e6f6f37e7186266ef730e0747fcca9f97a52341679ca327eda2d7e655ee8ae5",
          "sha256": "c2770415d3db9a0d3e27dce65711fea9a7e2d4f7809f2782b58bd327e1b6d9be",
          "sha1": "f14017d8a05755f66ddee52117880155426d75ff",
          "md5": "a5fdcbc76aadc32a4963163d091aedc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.10+1.20.jar",
          "url": "graphlib-1.0.0-alpha.10+1.20.jar",
          "size": 278063,
          "sha512": "edd6b7898dba3aa64b9f3503c26170bf8c6f3459906f9818947456e22e7ad3203e6f6f37e7186266ef730e0747fcca9f97a52341679ca327eda2d7e655ee8ae5",
          "sha256": "c2770415d3db9a0d3e27dce65711fea9a7e2d4f7809f2782b58bd327e1b6d9be",
          "sha1": "f14017d8a05755f66ddee52117880155426d75ff",
          "md5": "a5fdcbc76aadc32a4963163d091aedc8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.10+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.10+1.20-javadoc.jar",
          "size": 328774,
          "sha512": "c247599aabc74e06de863e27690ad1da46036ddbfaa91b04b57d4345d5a2f9dbdea076bd5306b65c1947949bdc8b8eadf1bb30e30fb09f76debd1bdd0f34ce9b",
          "sha256": "a8cdf83d11b312e6c45d9ce0c005ab9e8faeab7c1daacc267076a03dee768831",
          "sha1": "c4fea5abe996f9394c70704ee6c37afe19d98cd6",
          "md5": "840efc51e95a08aac1d9f6939a997829"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.10+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.10+1.20-sources.jar",
          "size": 200046,
          "sha512": "7732fb7590a329fdfe87b82859113cffa7bf89490f9aeb1d98f0122a55cff9c32aa010b94758dab97cfb2559fe536bd0b48deec82ee62387fd081af3c8ec8a85",
          "sha256": "61bd577d1314f4b2df291efa553190c4c85350da8ecb8bfd9c03391f8529456b",
          "sha1": "0458e9a70a3761aba03363ecd49ebf9ee4db5f37",
          "md5": "1cf00c85c2f726234c1beff2a9e8299f"
        }
      ]
    }
  ]
}
