{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-overlay",
    "version": "0.2.7+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.7+1.20.jar",
          "url": "kmodlib-overlay-0.2.7+1.20.jar",
          "size": 15897,
          "sha512": "805661e3068c20cd19199eb8b0b94ad88697630a1ce4ba778efe872905bcc8e4a04dd689df120fee93abb4bc3fd46c30fd2f2aae085659ca5e78d74585fd2eba",
          "sha256": "7a1b63d2c6f8ab659f111dbcdf5d45aac7f6811e7fa1fc0ceabd9bf93eff6640",
          "sha1": "74491c2f94306ec73de7ed943ab38c080a44cfff",
          "md5": "807664e17b1c58ffb02b144ff5e9ae7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.7+1.20.jar",
          "url": "kmodlib-overlay-0.2.7+1.20.jar",
          "size": 15897,
          "sha512": "805661e3068c20cd19199eb8b0b94ad88697630a1ce4ba778efe872905bcc8e4a04dd689df120fee93abb4bc3fd46c30fd2f2aae085659ca5e78d74585fd2eba",
          "sha256": "7a1b63d2c6f8ab659f111dbcdf5d45aac7f6811e7fa1fc0ceabd9bf93eff6640",
          "sha1": "74491c2f94306ec73de7ed943ab38c080a44cfff",
          "md5": "807664e17b1c58ffb02b144ff5e9ae7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.7+1.20-javadoc.jar",
          "url": "kmodlib-overlay-0.2.7+1.20-javadoc.jar",
          "size": 85459,
          "sha512": "8cf770ac1a9ff09bf427900a7017eec97395e89f354eb1bff8b261506d4718f6967c85b3d31021471d1a5a855176adf562c7cff0b7554099a1d4b723fa8a8411",
          "sha256": "72a6aaaa03435db5c65d70c04d19013027bea4533f4ed072b4e2952b9488222d",
          "sha1": "6c7c46a2f3e04f77ee9503aedb0a69dc23c22857",
          "md5": "6e096566e95b4ef51fe893ef6c27bdb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.7+1.20-sources.jar",
          "url": "kmodlib-overlay-0.2.7+1.20-sources.jar",
          "size": 13022,
          "sha512": "87f172e0a8afff6647c8dbfb34c4e02b47c5ad1a780468afcac723aa83a5932b45e0ebca00c6375aa1adabdaeab4d2666088e78e11833dddc9fee9fa4e351c81",
          "sha256": "c2d6ef54c8256c17588af9d0b16f11b74cb9530a161c9e6c682491be1a2b1664",
          "sha1": "f71a3cf63d608392d66ade60fba65322230c3c01",
          "md5": "99b8ee678cbb1da9ef26861ce7a24512"
        }
      ]
    }
  ]
}
