{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.2+1.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.2+1.19.4.jar",
          "url": "graphlib-1.0.0-alpha.2+1.19.4.jar",
          "size": 241854,
          "sha512": "f417bc24b2dc989d2dd0087a47c5589898f3024007e49fc710a4d881c4fb8ce9b0a0c886b496bc5e850a5cbe3b0834bdc10db2f7eec8c2e1bedc414294e837e1",
          "sha256": "2eca4620f9efc6e0bbb9a6533073e193f22a58e05849e887626b579a7b1512c1",
          "sha1": "5b97ebe71c2723f308c1f6ada1662522acab48fb",
          "md5": "265efc9b9ad37f395982661778b01950"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.2+1.19.4.jar",
          "url": "graphlib-1.0.0-alpha.2+1.19.4.jar",
          "size": 241854,
          "sha512": "f417bc24b2dc989d2dd0087a47c5589898f3024007e49fc710a4d881c4fb8ce9b0a0c886b496bc5e850a5cbe3b0834bdc10db2f7eec8c2e1bedc414294e837e1",
          "sha256": "2eca4620f9efc6e0bbb9a6533073e193f22a58e05849e887626b579a7b1512c1",
          "sha1": "5b97ebe71c2723f308c1f6ada1662522acab48fb",
          "md5": "265efc9b9ad37f395982661778b01950"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.2+1.19.4-sources.jar",
          "url": "graphlib-1.0.0-alpha.2+1.19.4-sources.jar",
          "size": 173747,
          "sha512": "cdf1c4a843f6cb01f58022fc3f743ce25b405ec336134781dd01f6ca7aa1bfd8661c5e26bfbb62179f376d9a69bdca8d2fda2a0384f1cfdd543afcb4c84a0ea5",
          "sha256": "922a37e81d104a0a3a914580a45d5b394774c72ba829522299ef7676315377d9",
          "sha1": "25f50b0bdcc797412a051906345572c569954023",
          "md5": "2a8206434a9b65e3b97b5cd6ddd07ea1"
        }
      ]
    }
  ]
}
