{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "jar-it",
    "version": "0.1.3+1.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-it-0.1.3+1.19.2.jar",
          "url": "jar-it-0.1.3+1.19.2.jar",
          "size": 249928,
          "sha512": "bf345d7776ac27c302e513bc20c7c409524d647b671f8aff21a0990c6408a9424136d6b57f2dd4ca49a6a3f8c4c8c086cb2526c4cb0da45e75edf7d593438637",
          "sha256": "e51b7edbc6f313e59c1fe9d199380eeb3663ae92c480ee7597ae7c061bf88846",
          "sha1": "5ff07a50132134239aeaa3f2f983c0ec2f1aab65",
          "md5": "deceb727a6ca4c46949d709a43884a21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.quiltmc.quilt-kotlin-libraries",
          "module": "quilt-kotlin-libraries",
          "version": {
            "requires": "0.1.3+kt.1.7.10+flk.1.8.2-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.7.1-pre.0.3+kneelawk"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jar-it-0.1.3+1.19.2.jar",
          "url": "jar-it-0.1.3+1.19.2.jar",
          "size": 249928,
          "sha512": "bf345d7776ac27c302e513bc20c7c409524d647b671f8aff21a0990c6408a9424136d6b57f2dd4ca49a6a3f8c4c8c086cb2526c4cb0da45e75edf7d593438637",
          "sha256": "e51b7edbc6f313e59c1fe9d199380eeb3663ae92c480ee7597ae7c061bf88846",
          "sha1": "5ff07a50132134239aeaa3f2f983c0ec2f1aab65",
          "md5": "deceb727a6ca4c46949d709a43884a21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-it-0.1.3+1.19.2-sources.jar",
          "url": "jar-it-0.1.3+1.19.2-sources.jar",
          "size": 36448,
          "sha512": "5ca52246c551a4b80ee4c44751f35c85820008bb4871dbe14a396c5c93962d3ffac6c16d5a7c4600d711594a1d70ce9535655b768a36ce7688fb5f8f775c9697",
          "sha256": "0bffd79782e9f66108ba892792c71c6e9838b8d65f71ed6f7e920919667a43e1",
          "sha1": "9d799ea26d3293d7f84b8d4aa904a19dd6e57f5c",
          "md5": "0f574194c9966c829a920146d3b94800"
        }
      ]
    }
  ]
}
