{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.30+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.30+1.20.jar",
          "url": "graphlib-1.0.0-alpha.30+1.20.jar",
          "size": 305341,
          "sha512": "6ea4394b0ae0b3238f1886d92e8270b9d66d47579d2054cb91a6bc1f7f52ab05d06fc8b035f425b17aade7d9a7dee0fd7231a3f16517c7176d1521e80477a882",
          "sha256": "8f83f3759061e86728ca53437d08fb252697361418a86fe8256424361d431474",
          "sha1": "4d30ccf1228b47fc72bbde53ed44b41fda652860",
          "md5": "85bf72a2fbdf7a22aec782bdad2712eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.30+1.20.jar",
          "url": "graphlib-1.0.0-alpha.30+1.20.jar",
          "size": 305341,
          "sha512": "6ea4394b0ae0b3238f1886d92e8270b9d66d47579d2054cb91a6bc1f7f52ab05d06fc8b035f425b17aade7d9a7dee0fd7231a3f16517c7176d1521e80477a882",
          "sha256": "8f83f3759061e86728ca53437d08fb252697361418a86fe8256424361d431474",
          "sha1": "4d30ccf1228b47fc72bbde53ed44b41fda652860",
          "md5": "85bf72a2fbdf7a22aec782bdad2712eb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.30+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.30+1.20-javadoc.jar",
          "size": 385114,
          "sha512": "01c6371e94d8109815c5504e546e49309eef49c0a1f9854208ad0e0e50568a1561debb685c2db06d5c928fe6e3919efb43ef12c60bca86d615c1923faac0f90b",
          "sha256": "d18b69ab730f5593f6f376ba1183a8bc106e6475035d4313b486e7b2b39aa809",
          "sha1": "9301201212695120398c6a336b55e6e6d2635c8b",
          "md5": "42468186f589a6b2445e3e7eb0a11c53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.30+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.30+1.20-sources.jar",
          "size": 219762,
          "sha512": "155fc4679c4f93907542465c627004740bf0566eedbeda9a90589d7946bce2d58f7b10b02b4fa0eece39a8b82090e113aabb0133d4e8ada0e5122098409da90d",
          "sha256": "2f15f256da3052954b6c670d1525aa2c6e2948a9b39b080249888102debdeea4",
          "sha1": "bad3960aec619d5fca847a932b464dd64ccd1522",
          "md5": "f4168f2eb05549100c5a42a9b4cab514"
        }
      ]
    }
  ]
}
