{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-overlay",
    "version": "0.2.4+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.4+1.20.jar",
          "url": "kmodlib-overlay-0.2.4+1.20.jar",
          "size": 15897,
          "sha512": "2745aa2865e3538440032763e0a9705bff0325926bd9f957ba8c3c53c8e79502714ee1847b44a3cca22aeeef177cf33e96927b18c0408410adb38214937905ab",
          "sha256": "684f6fe4ab558c4121ca7c23a5351128efd424a5c0fd54fdd9d8eac44c302f39",
          "sha1": "11551a2e223ef3a7fd82b780db288696626a1525",
          "md5": "f0d94ec8e5785d31293e08b5bdb6dffc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.4+1.20.jar",
          "url": "kmodlib-overlay-0.2.4+1.20.jar",
          "size": 15897,
          "sha512": "2745aa2865e3538440032763e0a9705bff0325926bd9f957ba8c3c53c8e79502714ee1847b44a3cca22aeeef177cf33e96927b18c0408410adb38214937905ab",
          "sha256": "684f6fe4ab558c4121ca7c23a5351128efd424a5c0fd54fdd9d8eac44c302f39",
          "sha1": "11551a2e223ef3a7fd82b780db288696626a1525",
          "md5": "f0d94ec8e5785d31293e08b5bdb6dffc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.4+1.20-javadoc.jar",
          "url": "kmodlib-overlay-0.2.4+1.20-javadoc.jar",
          "size": 85462,
          "sha512": "82ca168c68b9143adfac78e46b36554c1217f1dd0822dfd875fe0a193855ff8c8ec7740d0f079da6f80b072443df69af7359ea3a1f5026bd768e5ded61d8c29e",
          "sha256": "dcfd5631bde0fc442b82e6cc09539b74bc20156984d725ec42cb84459cbaba9c",
          "sha1": "f13d952d80b5cf53d36817910bfe365b4b3dfcc3",
          "md5": "9fb9a3c2531e430227b0dac9fbd7c607"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.4+1.20-sources.jar",
          "url": "kmodlib-overlay-0.2.4+1.20-sources.jar",
          "size": 13022,
          "sha512": "87f172e0a8afff6647c8dbfb34c4e02b47c5ad1a780468afcac723aa83a5932b45e0ebca00c6375aa1adabdaeab4d2666088e78e11833dddc9fee9fa4e351c81",
          "sha256": "c2d6ef54c8256c17588af9d0b16f11b74cb9530a161c9e6c682491be1a2b1664",
          "sha1": "f71a3cf63d608392d66ade60fba65322230c3c01",
          "md5": "99b8ee678cbb1da9ef26861ce7a24512"
        }
      ]
    }
  ]
}
