#!/usr/bin/env bash

mkdir -p "$HOME/dots"
cd "$HOME/dots"

BRANCH="$2"
case "$1" in
    new)
        git init
        git remote add origin git@github.com:Kneelawk/Dots.git
        git fetch origin
        echo "Creating new branch '$BRANCH'..."
        git checkout -b "$BRANCH"
        curl -fsSL 'https://kneelawk.com/assets/dots-install' -o dots-install
        echo "dots-install" >>.gitignore
        echo "*/.idea/" >>.gitignore
        chmod a+x dots-install
        bash ./dots-install get
        git add .
        git commit -m "Initial $BRANCH commit"
        git push -u origin "$BRANCH"
        ;;

    clone)
        git init
        git remote add origin git@github.com:Kneelawk/Dots.git
        git fetch origin
        echo "Cloning existing branch '$BRANCH'..."
        git checkout -b "$BRANCH" --track "origin/$BRANCH"
        git reset --hard "origin/$BRANCH"
        curl -fsSL 'https://kneelawk.com/assets/dots-install' -o dots-install
        chmod a+x dots-install
        bash ./dots-install put
        ;;

    update-installer)
        echo "Updating installer..."
        curl -fsSL 'https://kneelawk.com/assets/dots-install' -o dots-install
        ;;
esac

