{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "0.5.3+1.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-0.5.3+1.19.4.jar",
          "url": "graphlib-0.5.3+1.19.4.jar",
          "size": 226245,
          "sha512": "b3a46f59facd58003d5f535f5e59540c3671ac8bcf4ef19c46258fb03e4f119df3614a87ff3e6a4e4a5040198f941c534ffacf14193edea9fd1e96a2caf8e3c6",
          "sha256": "8bbf5f0338f87a7d707764c8d57352f0224d13f3e304be95182f2df3c7e14619",
          "sha1": "d950d2aad70ad3c68ee907b4316c99949ed44b5b",
          "md5": "d3844d7ebcb0fb7e3a6cf20363e789d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.5.3+1.19.4.jar",
          "url": "graphlib-0.5.3+1.19.4.jar",
          "size": 226245,
          "sha512": "b3a46f59facd58003d5f535f5e59540c3671ac8bcf4ef19c46258fb03e4f119df3614a87ff3e6a4e4a5040198f941c534ffacf14193edea9fd1e96a2caf8e3c6",
          "sha256": "8bbf5f0338f87a7d707764c8d57352f0224d13f3e304be95182f2df3c7e14619",
          "sha1": "d950d2aad70ad3c68ee907b4316c99949ed44b5b",
          "md5": "d3844d7ebcb0fb7e3a6cf20363e789d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.5.3+1.19.4-sources.jar",
          "url": "graphlib-0.5.3+1.19.4-sources.jar",
          "size": 162407,
          "sha512": "3fe1d17a09ccef476da7f642117e27dc20c38c6cd910c97bf9685789654f26dd1d218d5692226f4302b61fe22ac46887b2de9443d8e2b21e2df15ca6b54d4860",
          "sha256": "14bee1787c8c3087a46c2be684b401b0fef9b062e7c29cb0a130d8b2cf64bb9f",
          "sha1": "2b85b176913f3147577f10bdb68cdf39aff1cace",
          "md5": "5df4981b15632e490f5fb0e2c5da4ae2"
        }
      ]
    }
  ]
}
