{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.5+1.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.5+1.19.4.jar",
          "url": "graphlib-1.0.0-alpha.5+1.19.4.jar",
          "size": 251958,
          "sha512": "5fe23293e659e392d82f4ed4c6a6b817737987c21fdab7cd7b07212c1241c27f26585b8155978a39c4ff185bdb504db3ed053d76d18814bc7dd7226a0117653e",
          "sha256": "eee39d6ec985687564cc417947fb6abd8363b786d59abd39149ad181cfec4e2b",
          "sha1": "89aae6bd9be94beee8c4a1e66be52ded61a19694",
          "md5": "a590966aa6b629035bc6c026c5e79ef1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.5+1.19.4.jar",
          "url": "graphlib-1.0.0-alpha.5+1.19.4.jar",
          "size": 251958,
          "sha512": "5fe23293e659e392d82f4ed4c6a6b817737987c21fdab7cd7b07212c1241c27f26585b8155978a39c4ff185bdb504db3ed053d76d18814bc7dd7226a0117653e",
          "sha256": "eee39d6ec985687564cc417947fb6abd8363b786d59abd39149ad181cfec4e2b",
          "sha1": "89aae6bd9be94beee8c4a1e66be52ded61a19694",
          "md5": "a590966aa6b629035bc6c026c5e79ef1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.5+1.19.4-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.5+1.19.4-javadoc.jar",
          "size": 278092,
          "sha512": "bb0f70e2cfd101c81cd46b5dd9030e8c5bfedb41686816773b669606bee1382d3cc192df84fec34bcc6e03cce93139ccbf7a36fe053b7de21543062ed2174cfc",
          "sha256": "02066318ec3108e4bc64606ace3be2696073cb629a454dfecd38670bad1cce10",
          "sha1": "9922b5c6050fc65e349ff77bef8eadd13785559c",
          "md5": "8be8fb4f3c65c13c6ab1bd65c3a10efb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.5+1.19.4-sources.jar",
          "url": "graphlib-1.0.0-alpha.5+1.19.4-sources.jar",
          "size": 184733,
          "sha512": "51fe43131e311ccb951ab1af3dca33139d191a5e14b435e6edb7e6f50d2afb99032639331c92be976f254a7826935a96f109227d281a77c6e8df4dabc56aeafa",
          "sha256": "b28dfba2e2027419ad7cbae0b1ab34cf5614d13af1f4c554f1f7441daccc3aef",
          "sha1": "2ebeb2507b367627252f3a179f795062aaad2c8e",
          "md5": "f347d92c662fc32f09654ff153ce42e1"
        }
      ]
    }
  ]
}
