{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.32+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.32+1.20.jar",
          "url": "graphlib-1.0.0-alpha.32+1.20.jar",
          "size": 306694,
          "sha512": "d388a10551196dc71e7895e8af219ef8cc882dae497a9e530a72b80cb8f0d57e167f0d9a7f840b2b17dd0a28a81a9e1be0c04a2b456080fab61d93765eade504",
          "sha256": "37f7b62fab74411b40c601e11f350de6109b42cf9dab34be5673892a42f34982",
          "sha1": "3bdb688c7471570cd1536779b0d04ba1621062d7",
          "md5": "c777e04e0700d86a348b2e1d5d40842b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.32+1.20.jar",
          "url": "graphlib-1.0.0-alpha.32+1.20.jar",
          "size": 306694,
          "sha512": "d388a10551196dc71e7895e8af219ef8cc882dae497a9e530a72b80cb8f0d57e167f0d9a7f840b2b17dd0a28a81a9e1be0c04a2b456080fab61d93765eade504",
          "sha256": "37f7b62fab74411b40c601e11f350de6109b42cf9dab34be5673892a42f34982",
          "sha1": "3bdb688c7471570cd1536779b0d04ba1621062d7",
          "md5": "c777e04e0700d86a348b2e1d5d40842b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.32+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.32+1.20-javadoc.jar",
          "size": 388640,
          "sha512": "96094647e9bb68b822f2798b309b7a9b2e43475c518d2ba96f086fe1021086d4058e55f3485712c1cb3249a41a3d8acfc49f7ad4a470b7f8eaf45a920450cdd9",
          "sha256": "9e1e35a8499acfd94c14fb60fa13cc37f9d443ca1b0e11c95324a03188f9b469",
          "sha1": "b28ace8b53160ce83badab75b02180c340554d70",
          "md5": "be3e6818a9dd39b8fbee7faf8cf747e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.32+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.32+1.20-sources.jar",
          "size": 220772,
          "sha512": "b29e294b00007ed31b561495f7f2cd4de22594912b2386d816b6ad56f747ebef4c8d01fbe2951ae2b286619948cc1abe0e95cb3afda70fd29b326b9105c6f4ba",
          "sha256": "bce127a05e98793fac5537c52984b202b57aee85a4207a1fc4f8ea3b043ff9ae",
          "sha1": "d78214b749a6802ec4445948763d1d3a74189e8f",
          "md5": "38c22c3f9f16c82be54a90c0c80a02c4"
        }
      ]
    }
  ]
}
