{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.25+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.25+1.20.jar",
          "url": "graphlib-1.0.0-alpha.25+1.20.jar",
          "size": 300067,
          "sha512": "3d4368b65a93ea2d058e9dad5277767e340259b4e3e87e1e14a3f5cf3e24325fdd41e4b519f3bca7fb392a6d66296eb08db67ed90a6f2f731143515d4ac45b50",
          "sha256": "45a4861974946e7bfa0f0d2ad9d4ce83df1d788ba6f6e37c03cfb60d17b24dbb",
          "sha1": "f30354f4c92a9a0c880f7a0df9a5e2017da786c9",
          "md5": "a26f8a41cf21040550ccb0e7a7ea9038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.25+1.20.jar",
          "url": "graphlib-1.0.0-alpha.25+1.20.jar",
          "size": 300067,
          "sha512": "3d4368b65a93ea2d058e9dad5277767e340259b4e3e87e1e14a3f5cf3e24325fdd41e4b519f3bca7fb392a6d66296eb08db67ed90a6f2f731143515d4ac45b50",
          "sha256": "45a4861974946e7bfa0f0d2ad9d4ce83df1d788ba6f6e37c03cfb60d17b24dbb",
          "sha1": "f30354f4c92a9a0c880f7a0df9a5e2017da786c9",
          "md5": "a26f8a41cf21040550ccb0e7a7ea9038"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.25+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.25+1.20-javadoc.jar",
          "size": 378086,
          "sha512": "85c87fb4bbfaf8cb74b81a537d53c08bfb90b4efc26ac81be88a9c24d98b890ff502c71d15aaf87846be14d45eed8c15ee36a8c808fda27ac59eb09b5ac0d8b0",
          "sha256": "9c519eb19c8fea66eeb45f076bd2a5860699068cfdbfbfd77ca4e998c8effd23",
          "sha1": "c1077c959808cf4484fd623be434abd3accb73f6",
          "md5": "aeebc66bfa9ed3d24d955651e2bc8bc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.25+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.25+1.20-sources.jar",
          "size": 215486,
          "sha512": "8da9c4d441620d55bc82421e984bd81e835808fffc284b0d95811950cb7e652b645b0a12b4e99c625670fc7bff6403845f4b1879541308af117715e0a96f5d1a",
          "sha256": "447e7debd152d5f6e2547267ef1053843c8654ac54ba79fe04e1c0e45aabad0b",
          "sha1": "be61b56378181966fb5540e4cce95a05ce3f3b13",
          "md5": "0450cc547221a071cfb7bd64c18e0a65"
        }
      ]
    }
  ]
}
