{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "fabric",
    "version": "0.1.0+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-0.1.0+1.20.4.jar",
          "url": "fabric-0.1.0+1.20.4.jar",
          "size": 54377,
          "sha512": "4c8e2092ff487f5af19e2aa5ac2bf434650ec2376f82d49a5024a5faf1164a610e34b9e57f8c1f9de2fd2ae1e486d0588dfb05db95f2dea1e99bbbf0dc6d2f97",
          "sha256": "6edc5bb2540f632f1f264f0a5009b555e0eed87c25bce5ff82b993c0f5ff8c75",
          "sha1": "66a2e0a7cbafcffe9d4711ba60ed9169838c0999",
          "md5": "965a6d8d994b7dde6e6eb5bad6a1ec93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-0.1.0+1.20.4.jar",
          "url": "fabric-0.1.0+1.20.4.jar",
          "size": 54377,
          "sha512": "4c8e2092ff487f5af19e2aa5ac2bf434650ec2376f82d49a5024a5faf1164a610e34b9e57f8c1f9de2fd2ae1e486d0588dfb05db95f2dea1e99bbbf0dc6d2f97",
          "sha256": "6edc5bb2540f632f1f264f0a5009b555e0eed87c25bce5ff82b993c0f5ff8c75",
          "sha1": "66a2e0a7cbafcffe9d4711ba60ed9169838c0999",
          "md5": "965a6d8d994b7dde6e6eb5bad6a1ec93"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-0.1.0+1.20.4-dev-shadow.jar",
          "url": "fabric-0.1.0+1.20.4-dev-shadow.jar",
          "size": 52892,
          "sha512": "bd39d3232d7a846ef08944dc45a5e8ab79854130c4bbaca121a9fbe3051a457f69333f823310c3ef975949e7e0a3604256b7c00171d1a3bf3902d2866d457b62",
          "sha256": "e3c1ce12b80f5cd2fa58bc8ecd7c68f9e7ccfd0c59b430af8c8abcf9e3ffb395",
          "sha1": "56ba61a6a60d4a319f89e9e76e288d898e962ca3",
          "md5": "516a1c0b811a25bcab77d59dd9d7a360"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-0.1.0+1.20.4-javadoc.jar",
          "url": "fabric-0.1.0+1.20.4-javadoc.jar",
          "size": 174360,
          "sha512": "a412bc2f4a2f7ea6ca6d0a8c1ecedc848074cd582aad052c99a720ab91c9b875642c9d883cb9840158a06b52e3fb99bf2cb693a216a8860d17ce1ae81dbcaaa1",
          "sha256": "8edf84c848e602128bc272d61780ffa612a1adfcf671aa34ca0a813c8b2d1e2a",
          "sha1": "c95f4a0b01891d6510cb9ab8f76ec6cc9463d292",
          "md5": "fceeef2f5cbf23aedf1456cc170a161d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-0.1.0+1.20.4-sources.jar",
          "url": "fabric-0.1.0+1.20.4-sources.jar",
          "size": 49836,
          "sha512": "430be257137a06be21480d15f65696ed8be80608474d8c5634ea30ff4b8dbdfbc1e4dc5ae6885f75de40799d7f96640d5a3d5c589e1dc2d5e8b9f64a9dda96a4",
          "sha256": "ca1d09ea1b319d701f0916ccc709d2d1a6ed3215ce16e6db55511fd4e1076170",
          "sha1": "bd90ceceb830fdb5d18e419612a74d3196de9333",
          "md5": "32c17ca13e018400230830f2e3d9d975"
        }
      ]
    }
  ]
}
