{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.35+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.35+1.20.jar",
          "url": "graphlib-1.0.0-alpha.35+1.20.jar",
          "size": 307407,
          "sha512": "d578550b050b7a03230a51a0115a90cdbe01a12504c6da669e617e8cafbeb2981292f976c99a4e08bd3028d4dad7b1cdc0807bf33ea816592c75bc9fd41f3122",
          "sha256": "0e836dff0cd8041bcb0492e3c7d53fa99c07a2d2354b1434c5c2d5b1b0eb0768",
          "sha1": "140992f2ca90cfeb4c66bde98631c60f3e7486fe",
          "md5": "75eab0c778fd6ca404de2099c101ba01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.35+1.20.jar",
          "url": "graphlib-1.0.0-alpha.35+1.20.jar",
          "size": 307407,
          "sha512": "d578550b050b7a03230a51a0115a90cdbe01a12504c6da669e617e8cafbeb2981292f976c99a4e08bd3028d4dad7b1cdc0807bf33ea816592c75bc9fd41f3122",
          "sha256": "0e836dff0cd8041bcb0492e3c7d53fa99c07a2d2354b1434c5c2d5b1b0eb0768",
          "sha1": "140992f2ca90cfeb4c66bde98631c60f3e7486fe",
          "md5": "75eab0c778fd6ca404de2099c101ba01"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.35+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.35+1.20-javadoc.jar",
          "size": 385227,
          "sha512": "c14e42065144188fba1efb9a716c5b0ef355566278cedd3de0f890208e795d49e4f82a246db9d6fee772aa600c6d277158870631fdff54c5c819d96d417cab18",
          "sha256": "e5e7d8f2d8d326b393200f658434ef2d5260933f7f0f8b2fc55ce0af416426be",
          "sha1": "0ff232797c3be41e2f43e11e66fafe6f5d36391d",
          "md5": "b4bad86b790eb870e6aa84c23b3af670"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.35+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.35+1.20-sources.jar",
          "size": 221087,
          "sha512": "30ce490c76f6828b265ec279fcc01f6e52d3cc0e699046755fce1d1850dd0a596bafdca70a8ccb9631bde9cfbce4dfae49369b04905b877210521de12021cdc5",
          "sha256": "1bf2dd9a697341f4f998cbe83f3f276560249747b0e4fa9ee5407a2483c8a237",
          "sha1": "c19abe857d79e276fa5e18f1dad3c577451c7dc2",
          "md5": "5dd85c88e9d759468e69e0f3ba55ddfc"
        }
      ]
    }
  ]
}
