{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.1+1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.1+1.19.3.jar",
          "url": "graphlib-1.0.0-alpha.1+1.19.3.jar",
          "size": 241732,
          "sha512": "d2c9c134fbfacb41e41fbb10b0c0521d77fa56acb27aff2b2e078090534f952db0adb473a9032b8a358168fb7ea664904027414163c6ccf31f9b4a560b3bfb6a",
          "sha256": "a24b2d0909fa451e41413f5c30f2a7d3be87b104cc7dff5cab96ed9adf6deafa",
          "sha1": "71273c972f2dfe9a9948bf05b664c3876e0e6b93",
          "md5": "ac30638bf60e9e87d929b33ea3652631"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.1+1.19.3.jar",
          "url": "graphlib-1.0.0-alpha.1+1.19.3.jar",
          "size": 241732,
          "sha512": "d2c9c134fbfacb41e41fbb10b0c0521d77fa56acb27aff2b2e078090534f952db0adb473a9032b8a358168fb7ea664904027414163c6ccf31f9b4a560b3bfb6a",
          "sha256": "a24b2d0909fa451e41413f5c30f2a7d3be87b104cc7dff5cab96ed9adf6deafa",
          "sha1": "71273c972f2dfe9a9948bf05b664c3876e0e6b93",
          "md5": "ac30638bf60e9e87d929b33ea3652631"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.1+1.19.3-sources.jar",
          "url": "graphlib-1.0.0-alpha.1+1.19.3-sources.jar",
          "size": 173741,
          "sha512": "42a29f94cbc946efc596f7e476232516f8485e7d71939d6b8f9b986d629ec46ad1d2b26e886bcf25dc665f285d267acf82b5312c8f1a50525f45883a33b5e285",
          "sha256": "0d63556f768028aab16541d86f904c289bcf25425e900f4382163b60445da624",
          "sha1": "e2f0e830bdc1e5fa2ac52866123e2907d7aafc66",
          "md5": "81654d423a39afdbe793e0af089e9d9f"
        }
      ]
    }
  ]
}
