{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "wired-redstone",
    "version": "0.7.5+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.7.5+1.20.1.jar",
          "url": "wired-redstone-0.7.5+1.20.1.jar",
          "size": 3941749,
          "sha512": "af6e088f68621ecadf8e4e61907fa618eaf2ecc164f54fc5df768dc24b422f62f55d7d953a7981fbef17054a77301ecd4f834ef0771c7a55296c8903b3aead14",
          "sha256": "4faf5f8631b2518f3d89a5c8be35d74da9f28038949427e7948baee74c94279d",
          "sha1": "ce3ba20aba1cd0f372d8f6cf66b49bde8c7cef83",
          "md5": "e0f3865915c864d53aff017df1824222"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.8"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-config",
          "version": {
            "requires": "1.0.0-beta.6"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-json5",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.9.3+kotlin.1.8.20"
          }
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libmultipart-all",
          "version": {
            "requires": "0.11.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.kneelawk",
          "module": "graphlib",
          "version": {
            "requires": "1.3.1+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.7.5+1.20.1.jar",
          "url": "wired-redstone-0.7.5+1.20.1.jar",
          "size": 3941749,
          "sha512": "af6e088f68621ecadf8e4e61907fa618eaf2ecc164f54fc5df768dc24b422f62f55d7d953a7981fbef17054a77301ecd4f834ef0771c7a55296c8903b3aead14",
          "sha256": "4faf5f8631b2518f3d89a5c8be35d74da9f28038949427e7948baee74c94279d",
          "sha1": "ce3ba20aba1cd0f372d8f6cf66b49bde8c7cef83",
          "md5": "e0f3865915c864d53aff017df1824222"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.7.5+1.20.1-shadow-dev.jar",
          "url": "wired-redstone-0.7.5+1.20.1-shadow-dev.jar",
          "size": 2790896,
          "sha512": "086d1944e2b09e3a1435dadd6d5426c30f11756ef2d851e22ffef71300e07e5af3f5c84fc0a8363e659451f9a424a25bdc982f5aa511e17f92b4b07f497532b9",
          "sha256": "3c1ecddc33baa43c9af285fb4a2f063f051d8c163eedc2bc88e37553e58a7b3a",
          "sha1": "904e69f5dafd12d0f3860abab275bdec24412d47",
          "md5": "d4c3016ff7134dec442ec2b0c33e46bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.7.5+1.20.1-sources.jar",
          "url": "wired-redstone-0.7.5+1.20.1-sources.jar",
          "size": 2327354,
          "sha512": "c8502406de424e5b1e28e15e3398902cfc8a7aa3d46a478cb49d4f63789b361174040c61d3c51e5471458cdb62e4fec9f6b49a289edd807671ef33d46d8c21e7",
          "sha256": "ebcc50ef1db72e784c68e8e028376fa5103af46df69c2e3f58053f444c6e162f",
          "sha1": "344ebd8047e98294c2176d5df3f14f198d539c94",
          "md5": "21070bf15012dc7eaf8f5ed5aebf605f"
        }
      ]
    }
  ]
}
