{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk.graphlib",
    "module": "core-neoforge",
    "version": "2.0.0-alpha.17+1.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "codextra-neoforge",
          "version": {
            "requires": "1.1.0+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-neoforge-2.0.0-alpha.17+1.20.6.jar",
          "url": "core-neoforge-2.0.0-alpha.17+1.20.6.jar",
          "size": 410863,
          "sha512": "cc7396ff140bd421c1f7d26aa857f53d43f3b583ecd03cc79b9bb5fecba536eefccf7c61f0bd577692ed42c1240b1b29de9ec46df352ffb3d7340018dbcb1296",
          "sha256": "a8faa3c9ee952c7513e49a715a33ef3afb6117dd53b657fe312a125b0b4593b5",
          "sha1": "93d1ad1e645f0e9c5b2ba3f036774ed1da326a50",
          "md5": "962eaf501fecb5e88062b37e1662f498"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "codextra-neoforge",
          "version": {
            "requires": "1.1.0+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-neoforge-2.0.0-alpha.17+1.20.6.jar",
          "url": "core-neoforge-2.0.0-alpha.17+1.20.6.jar",
          "size": 410863,
          "sha512": "cc7396ff140bd421c1f7d26aa857f53d43f3b583ecd03cc79b9bb5fecba536eefccf7c61f0bd577692ed42c1240b1b29de9ec46df352ffb3d7340018dbcb1296",
          "sha256": "a8faa3c9ee952c7513e49a715a33ef3afb6117dd53b657fe312a125b0b4593b5",
          "sha1": "93d1ad1e645f0e9c5b2ba3f036774ed1da326a50",
          "md5": "962eaf501fecb5e88062b37e1662f498"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-neoforge-2.0.0-alpha.17+1.20.6-sources.jar",
          "url": "core-neoforge-2.0.0-alpha.17+1.20.6-sources.jar",
          "size": 238527,
          "sha512": "eb79def33f45f3286a799cc0c7fc4fc4208b80a535043b70d39500ec89361922b5ce96da106b69c6cfea4e81e70359af3b17f078162b08b19097d92df3291dbd",
          "sha256": "dafb55b272158a1a9f94fc1b50f3b34159e924e1694046df8325c7cb388412b8",
          "sha1": "f9ef700799a0dcc42bc316abd0e191341eac83d7",
          "md5": "2caa0733a7a2e5428acc5dbe55b41091"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-neoforge-2.0.0-alpha.17+1.20.6-javadoc.jar",
          "url": "core-neoforge-2.0.0-alpha.17+1.20.6-javadoc.jar",
          "size": 379230,
          "sha512": "e6c3bddbba640e8705765645a98d832e00951ad2bcb6dd4e7a1576867e1b02ac17428066f1985ba0d2e462d47a2a8c1106631d53d6093fe54f5bda4f8bee4306",
          "sha256": "1ef2b89ab794fefb176ae1a553bf59b3a903dda94edb64ac542d6becc8171852",
          "sha1": "3c36023035340299803834d6e9399bc0b187f1af",
          "md5": "cd8b11c2859e259d35056f445181557d"
        }
      ]
    }
  ]
}
