{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-all",
    "version": "0.2.6+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-blockmodel",
          "version": {
            "requires": "0.2.6+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-overlay",
          "version": {
            "requires": "0.2.6+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-renderlayer",
          "version": {
            "requires": "0.2.6+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-all-0.2.6+1.20.jar",
          "url": "kmodlib-all-0.2.6+1.20.jar",
          "size": 129561,
          "sha512": "61417a7b0c7a6b22b52b4a5805c147f53d3b5fc6ee77387e69af582bcba9d2cbbc61632f906cf21827a244ad290239339a4af0cda45125cee99d3e2f0354b8d4",
          "sha256": "e27ed41a9922c42f0b833350a587a5955d5d4ac5baaa86f4fddbddaa59b10e14",
          "sha1": "22940965d993e7deb6982d7b9ba1f4823b9ebd8d",
          "md5": "1ae24004552864c08a7122c8146cd4f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-blockmodel",
          "version": {
            "requires": "0.2.6+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-overlay",
          "version": {
            "requires": "0.2.6+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-renderlayer",
          "version": {
            "requires": "0.2.6+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-all-0.2.6+1.20.jar",
          "url": "kmodlib-all-0.2.6+1.20.jar",
          "size": 129561,
          "sha512": "61417a7b0c7a6b22b52b4a5805c147f53d3b5fc6ee77387e69af582bcba9d2cbbc61632f906cf21827a244ad290239339a4af0cda45125cee99d3e2f0354b8d4",
          "sha256": "e27ed41a9922c42f0b833350a587a5955d5d4ac5baaa86f4fddbddaa59b10e14",
          "sha1": "22940965d993e7deb6982d7b9ba1f4823b9ebd8d",
          "md5": "1ae24004552864c08a7122c8146cd4f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-all-0.2.6+1.20-javadoc.jar",
          "url": "kmodlib-all-0.2.6+1.20-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-all-0.2.6+1.20-sources.jar",
          "url": "kmodlib-all-0.2.6+1.20-sources.jar",
          "size": 9423,
          "sha512": "0253796e77fe4b8eacf50d3c6a290de241de16a063fade667d7c8875a1d663df6718f55672f33da8275f4c83d53fc777d6827c1761a19280c4e9a58bd5274257",
          "sha256": "93b7cd40f8984ef30bfd3dbf1feaaa068b0639177d6d7aed6d86bbcd9a6bf1ff",
          "sha1": "5a22f8a952d8687dbbb76fbc877ab45b959386d9",
          "md5": "e32660574b00459cb4f492af5bf31882"
        }
      ]
    }
  ]
}
