{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-all",
    "version": "0.2.5+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-blockmodel",
          "version": {
            "requires": "0.2.5+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-overlay",
          "version": {
            "requires": "0.2.5+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-renderlayer",
          "version": {
            "requires": "0.2.5+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-all-0.2.5+1.20.jar",
          "url": "kmodlib-all-0.2.5+1.20.jar",
          "size": 129559,
          "sha512": "5f2195c3eee018663c230ec87611778575ca03d5f191a6c9bbef99b521de6169a8c9a0e5a535b0689effa01e090b8c412080f4a6a2544aeee8c360c0e1eb48fe",
          "sha256": "b927da76f5401106289c8961d2f186c87b715e2c6cd5689d3b2e99df2ba9ae10",
          "sha1": "93cfe2391ab71ae8b05a4b0cc36cb3b96dff882b",
          "md5": "11a8d5cea1a50fa8b05031b82e42a423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-blockmodel",
          "version": {
            "requires": "0.2.5+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-overlay",
          "version": {
            "requires": "0.2.5+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-renderlayer",
          "version": {
            "requires": "0.2.5+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-all-0.2.5+1.20.jar",
          "url": "kmodlib-all-0.2.5+1.20.jar",
          "size": 129559,
          "sha512": "5f2195c3eee018663c230ec87611778575ca03d5f191a6c9bbef99b521de6169a8c9a0e5a535b0689effa01e090b8c412080f4a6a2544aeee8c360c0e1eb48fe",
          "sha256": "b927da76f5401106289c8961d2f186c87b715e2c6cd5689d3b2e99df2ba9ae10",
          "sha1": "93cfe2391ab71ae8b05a4b0cc36cb3b96dff882b",
          "md5": "11a8d5cea1a50fa8b05031b82e42a423"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-all-0.2.5+1.20-javadoc.jar",
          "url": "kmodlib-all-0.2.5+1.20-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-all-0.2.5+1.20-sources.jar",
          "url": "kmodlib-all-0.2.5+1.20-sources.jar",
          "size": 9423,
          "sha512": "0253796e77fe4b8eacf50d3c6a290de241de16a063fade667d7c8875a1d663df6718f55672f33da8275f4c83d53fc777d6827c1761a19280c4e9a58bd5274257",
          "sha256": "93b7cd40f8984ef30bfd3dbf1feaaa068b0639177d6d7aed6d86bbcd9a6bf1ff",
          "sha1": "5a22f8a952d8687dbbb76fbc877ab45b959386d9",
          "md5": "e32660574b00459cb4f492af5bf31882"
        }
      ]
    }
  ]
}
