{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-blockmodel",
    "version": "0.2.4+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-rendertag",
          "version": {
            "requires": "0.2.4+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-blockmodel-0.2.4+1.20.jar",
          "url": "kmodlib-blockmodel-0.2.4+1.20.jar",
          "size": 99189,
          "sha512": "3ec3b538839e1ec6c46a9bd209db9f6406a6367393bb98340fb1418b0da33b9233f3bdf94e179396b574d8540d55edeb9431d68d40abf3bcd1946b207306e6f0",
          "sha256": "ab0ae46ec9ba84c9007c2e4e19cd1420ee761d12c35ff45f16a6981fe82e2192",
          "sha1": "fc02cc1da7f59ece03ea1bb4b3a0b980a48c6f6c",
          "md5": "c741e22ea557808e7fbf4226b5c43bce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-rendertag",
          "version": {
            "requires": "0.2.4+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-blockmodel-0.2.4+1.20.jar",
          "url": "kmodlib-blockmodel-0.2.4+1.20.jar",
          "size": 99189,
          "sha512": "3ec3b538839e1ec6c46a9bd209db9f6406a6367393bb98340fb1418b0da33b9233f3bdf94e179396b574d8540d55edeb9431d68d40abf3bcd1946b207306e6f0",
          "sha256": "ab0ae46ec9ba84c9007c2e4e19cd1420ee761d12c35ff45f16a6981fe82e2192",
          "sha1": "fc02cc1da7f59ece03ea1bb4b3a0b980a48c6f6c",
          "md5": "c741e22ea557808e7fbf4226b5c43bce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-blockmodel-0.2.4+1.20-javadoc.jar",
          "url": "kmodlib-blockmodel-0.2.4+1.20-javadoc.jar",
          "size": 227837,
          "sha512": "958fce668b4e80fe60eb61b4ebf39df8182294a785982ffc2f192e3a9a10d214f3b56416ad86db245a622f1c604232d747b25cd764cc2cd60ef960c5aa93c906",
          "sha256": "2ddb215b7c28e48f28a6aeffbc119987125040d10adf6b2a22c57169e3172aa3",
          "sha1": "ac295d817a9537847c99885099226df1e89179b1",
          "md5": "df98915ca050b561f7a1f9deebd2cb45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-blockmodel-0.2.4+1.20-sources.jar",
          "url": "kmodlib-blockmodel-0.2.4+1.20-sources.jar",
          "size": 43525,
          "sha512": "fb78b28e29ffa85e3af9d0c9a4ee1cae8a1ea21ef4914119ce3c3b42254cf2421e01b0b157aa685f6244a6c0d6843355ce4d9986015f602e37c4118f00d21809",
          "sha256": "34fac3e49e4dd8a670bc5a110fb831d52c1751da4bcd89b178d9619d6165e380",
          "sha1": "6b99862de256cfa20c102c0b4c6ba7f354bff928",
          "md5": "ced91852d1d7365c8ba626a45a065979"
        }
      ]
    }
  ]
}
