{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-all",
    "version": "0.2.12+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-blockmodel",
          "version": {
            "requires": "0.2.12+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-overlay",
          "version": {
            "requires": "0.2.12+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-renderlayer",
          "version": {
            "requires": "0.2.12+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-all-0.2.12+1.20.jar",
          "url": "kmodlib-all-0.2.12+1.20.jar",
          "size": 133130,
          "sha512": "fd0a921a620898405c3e846b81cc19f5292b9328da913ee731c410bfb9d1e1fe9cd322aebf005dfe82e5aad4dbca5e61056bd57622d3c243b453c4aa5d062603",
          "sha256": "3f517b9cef95aed5791e11c3b9a6e207f7d704a68ec3606b4bd07dba3ca26682",
          "sha1": "197f5b3df7774f631b1466de6b99b394d8c1afab",
          "md5": "eab551ddf6279a640cf99781e2d5794d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kneelawk",
          "module": "kmodlib-blockmodel",
          "version": {
            "requires": "0.2.12+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-overlay",
          "version": {
            "requires": "0.2.12+1.20"
          }
        },
        {
          "group": "com.kneelawk",
          "module": "kmodlib-renderlayer",
          "version": {
            "requires": "0.2.12+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kmodlib-all-0.2.12+1.20.jar",
          "url": "kmodlib-all-0.2.12+1.20.jar",
          "size": 133130,
          "sha512": "fd0a921a620898405c3e846b81cc19f5292b9328da913ee731c410bfb9d1e1fe9cd322aebf005dfe82e5aad4dbca5e61056bd57622d3c243b453c4aa5d062603",
          "sha256": "3f517b9cef95aed5791e11c3b9a6e207f7d704a68ec3606b4bd07dba3ca26682",
          "sha1": "197f5b3df7774f631b1466de6b99b394d8c1afab",
          "md5": "eab551ddf6279a640cf99781e2d5794d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-all-0.2.12+1.20-javadoc.jar",
          "url": "kmodlib-all-0.2.12+1.20-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-all-0.2.12+1.20-sources.jar",
          "url": "kmodlib-all-0.2.12+1.20-sources.jar",
          "size": 9422,
          "sha512": "0b6dd6aef48aed77c0334d7fd0fe41d132c0ddbcb46cfd760ea070197fd5d7b300db9fffcb4675408056792c665f2ae0f3d3523d32b540dcb2cd6790fc7da0d8",
          "sha256": "a53e26e697a6a4281800a8cc82b73b0a41f72746f3882278188b47fecad4f68d",
          "sha1": "918b403bc554e46804c12368fe546493be213a31",
          "md5": "0dfe6e00b9428e34052460e7d11bc8fd"
        }
      ]
    }
  ]
}
