{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "jar-it",
    "version": "0.1.9+1.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-it-0.1.9+1.19.2.jar",
          "url": "jar-it-0.1.9+1.19.2.jar",
          "size": 347081,
          "sha512": "9bc2b48fd27f9cc436274aff797371b0f95782389aa59d7d3783a98b552a8615ce84eed78ac208510b365cbc7ef752fe375ffd9cd558bcb2330d19c2b86cfc8b",
          "sha256": "4316e484e0a235403cf56f0c500653b7c2b2438aeb4c85d6755e546dd97c88e4",
          "sha1": "6aa7650628f579ee773160a904af461eadbf8b6f",
          "md5": "4531654183346e6eab04369a0375c63b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.quiltmc.quilt-kotlin-libraries",
          "module": "quilt-kotlin-libraries",
          "version": {
            "requires": "0.1.3+kt.1.7.10+flk.1.8.2-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.7.1-pre.0.3+kneelawk"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jar-it-0.1.9+1.19.2.jar",
          "url": "jar-it-0.1.9+1.19.2.jar",
          "size": 347081,
          "sha512": "9bc2b48fd27f9cc436274aff797371b0f95782389aa59d7d3783a98b552a8615ce84eed78ac208510b365cbc7ef752fe375ffd9cd558bcb2330d19c2b86cfc8b",
          "sha256": "4316e484e0a235403cf56f0c500653b7c2b2438aeb4c85d6755e546dd97c88e4",
          "sha1": "6aa7650628f579ee773160a904af461eadbf8b6f",
          "md5": "4531654183346e6eab04369a0375c63b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-it-0.1.9+1.19.2-sources.jar",
          "url": "jar-it-0.1.9+1.19.2-sources.jar",
          "size": 109860,
          "sha512": "0ca74ec329b51bf733935dbdc1ef33d7fd402af9c432ea2bae3b634aae0af29debdcdcb567a91868f5771d7eb878441ebf2c7185c202badcfa7267ebed7f0e66",
          "sha256": "a6f58a2953044baca7754ede93c60883de4d7926ac352ae98c94a5b668a0c600",
          "sha1": "236f574a95d1b416f910382554dc961bc742f212",
          "md5": "da3aa78d2b6466aee912a9ef598d9b42"
        }
      ]
    }
  ]
}
