{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "wired-redstone",
    "version": "0.7.6+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.7.6+1.20.1.jar",
          "url": "wired-redstone-0.7.6+1.20.1.jar",
          "size": 3947943,
          "sha512": "1c2a30a9680fc938afc6c18e292761d0b1e3e1f1f9fffa2b9f82d3252d8a1d75de69f78c0f179baf218cb75e2381e65947c98a5d42caaaa064e1a25c45492763",
          "sha256": "76af70168c232bde100b40c05246a9fc9941f82fceb87d6518e94c192e821415",
          "sha1": "6b992a02282d78c5ceff5db6a03578fb0b26a6dc",
          "md5": "820784950468478b426039f6ff1d2e41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.8"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-config",
          "version": {
            "requires": "1.0.0-beta.6"
          }
        },
        {
          "group": "org.quiltmc",
          "module": "quilt-json5",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.9.3+kotlin.1.8.20"
          }
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libmultipart-all",
          "version": {
            "requires": "0.11.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.kneelawk",
          "module": "graphlib",
          "version": {
            "requires": "1.3.2+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "wired-redstone-0.7.6+1.20.1.jar",
          "url": "wired-redstone-0.7.6+1.20.1.jar",
          "size": 3947943,
          "sha512": "1c2a30a9680fc938afc6c18e292761d0b1e3e1f1f9fffa2b9f82d3252d8a1d75de69f78c0f179baf218cb75e2381e65947c98a5d42caaaa064e1a25c45492763",
          "sha256": "76af70168c232bde100b40c05246a9fc9941f82fceb87d6518e94c192e821415",
          "sha1": "6b992a02282d78c5ceff5db6a03578fb0b26a6dc",
          "md5": "820784950468478b426039f6ff1d2e41"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.7.6+1.20.1-shadow-dev.jar",
          "url": "wired-redstone-0.7.6+1.20.1-shadow-dev.jar",
          "size": 2794105,
          "sha512": "30cec6cd9e11b2b07721e9c0ca69cb1810a7bb117eec20a965334ebf6bed1f9ef32a86df06acda74b2bf7f949d17354100e80aac058518c4d311282a5d772090",
          "sha256": "7e6a8ec800f91971b169c4da2f5d37cc6523c499740918346a68a7df46067058",
          "sha1": "3efbccfb18b7ab0e264d307db86170d108706933",
          "md5": "5f8aaac71e466f5884c7f3680bc75b52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wired-redstone-0.7.6+1.20.1-sources.jar",
          "url": "wired-redstone-0.7.6+1.20.1-sources.jar",
          "size": 2329316,
          "sha512": "e8351eb534bb7b7171210c27177c132d0d731b46baa22b81755c93945bf090bb8563d4b59341359baaa8b66177e0f42d83ab36eee7052b48f395e924d3ecd0b2",
          "sha256": "e8e1e8f0bb64a2ff010ad39ea5983f3a3d21769e7b4171d4c2a10c55355c2a1c",
          "sha1": "acc86c123563ba22f4f03e737a32383fbe0a6898",
          "md5": "f8697b7734f0a4072a29b0e363df35bb"
        }
      ]
    }
  ]
}
