{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "0.4.8+1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-0.4.8+1.19.3.jar",
          "url": "graphlib-0.4.8+1.19.3.jar",
          "size": 226151,
          "sha512": "f34faafcd5ac0f67c3042453382d9c4b6bee8b84a423ec3b2f1e366648711effd1a73d26644d65cfa47b75a69e4a6c4658e4c02ad4b0611891f182b3b0a97a1a",
          "sha256": "15e8619b482398111085f47924f2a34bf4299ab982ebbdc07048c5216f460e7b",
          "sha1": "2a87e3b88ca7558002c2da16e2b9b6d84d13132c",
          "md5": "73fef805f2c0f9e2ea0dafe6e4c50982"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.4.8+1.19.3.jar",
          "url": "graphlib-0.4.8+1.19.3.jar",
          "size": 226151,
          "sha512": "f34faafcd5ac0f67c3042453382d9c4b6bee8b84a423ec3b2f1e366648711effd1a73d26644d65cfa47b75a69e4a6c4658e4c02ad4b0611891f182b3b0a97a1a",
          "sha256": "15e8619b482398111085f47924f2a34bf4299ab982ebbdc07048c5216f460e7b",
          "sha1": "2a87e3b88ca7558002c2da16e2b9b6d84d13132c",
          "md5": "73fef805f2c0f9e2ea0dafe6e4c50982"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.4.8+1.19.3-sources.jar",
          "url": "graphlib-0.4.8+1.19.3-sources.jar",
          "size": 162421,
          "sha512": "e9cba8fc10a39349a47ac3ce095629b9c114f997ba3a242e04b40b7695ffd46c5cf47b223ac22e4823c630841600070f251db1cb10fa1a09d66fc952938a64c0",
          "sha256": "e792e01f500831b19bf6405d5ee1f3624d48fe81a0da59fbcd0590c7da642e06",
          "sha1": "75cb97d5d36e2fcfe2a75899a267399cc2fc3e82",
          "md5": "82214be6e4e04d79a41cb3a255215d65"
        }
      ]
    }
  ]
}
