{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.27+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.27+1.20.jar",
          "url": "graphlib-1.0.0-alpha.27+1.20.jar",
          "size": 303659,
          "sha512": "bd2650df49aa6ceef8f43e448844479b2c7469e31102e6f7781f2fff73ddf3cf425a5520d83f2d7b74d85a414f83969f5e483a7b0fce7bbe35e8c23d1afd8cdd",
          "sha256": "ce531cf33933b8490b0ba484bfc0530e18fa55c90aeebc7ef34f6176e129335d",
          "sha1": "822a88313c3aa718cf5bfa57e6a59ef2fd8597c5",
          "md5": "549baa96f02bf698264c9192dc80e187"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.27+1.20.jar",
          "url": "graphlib-1.0.0-alpha.27+1.20.jar",
          "size": 303659,
          "sha512": "bd2650df49aa6ceef8f43e448844479b2c7469e31102e6f7781f2fff73ddf3cf425a5520d83f2d7b74d85a414f83969f5e483a7b0fce7bbe35e8c23d1afd8cdd",
          "sha256": "ce531cf33933b8490b0ba484bfc0530e18fa55c90aeebc7ef34f6176e129335d",
          "sha1": "822a88313c3aa718cf5bfa57e6a59ef2fd8597c5",
          "md5": "549baa96f02bf698264c9192dc80e187"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.27+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.27+1.20-javadoc.jar",
          "size": 383054,
          "sha512": "77bed3bf770511194f86b6eec0f9d81e64011100f89d33d4bbb36285d340a30eded58e38bd4e8a1ff77c2d7a173960abf520286a1ab7e18ad6be83a2c0df53e3",
          "sha256": "fb6b2e94b4a10b8e2317068e423d4f7f430b4ffbf117d85ff8eb3d12a3f2645a",
          "sha1": "9ff791db3c0664c4e7343db4cef3a3f48e232fb8",
          "md5": "164d4cc718e83e2ea629a0a88223748d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.27+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.27+1.20-sources.jar",
          "size": 218695,
          "sha512": "caf6ef77ce373d25f949785680b9c706c953f295065e405ea051c7b59deceb6421431d53ef45324900f7c4b0511791d50c2523f8aefe9263739bf744376a534c",
          "sha256": "4fab3f01cf7cb97644bc61411aed97bc1fe574310e2612e70eab006bd619a6fc",
          "sha1": "7c8d3d3a3856a419038af8c2f98b6652eb3ec610",
          "md5": "1b82f5f65bfd4e7051947c3c74cc8330"
        }
      ]
    }
  ]
}
