{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk.graphlib",
    "module": "core-xplat-intermediary",
    "version": "2.0.0-alpha.8+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4.jar",
          "url": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4.jar",
          "size": 282188,
          "sha512": "8a5f75053fca0bdb1e7c0399566b092c2876b2dd7c86dbd6034aebfb2586b2e7b5e919ca434b33625ccb6a497575cb31f52969bb7b1c7fce67b1e482c87aa94b",
          "sha256": "bbeaa896897c217e639e73b824a96226e64fe7561471a1489ac876e73c2a16f4",
          "sha1": "5efc34c14a9afb2d752301dec39843e9ce5b50bc",
          "md5": "21572f41bd714b6e1488707a72215881"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4.jar",
          "url": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4.jar",
          "size": 282188,
          "sha512": "8a5f75053fca0bdb1e7c0399566b092c2876b2dd7c86dbd6034aebfb2586b2e7b5e919ca434b33625ccb6a497575cb31f52969bb7b1c7fce67b1e482c87aa94b",
          "sha256": "bbeaa896897c217e639e73b824a96226e64fe7561471a1489ac876e73c2a16f4",
          "sha1": "5efc34c14a9afb2d752301dec39843e9ce5b50bc",
          "md5": "21572f41bd714b6e1488707a72215881"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4-javadoc.jar",
          "url": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4-javadoc.jar",
          "size": 361609,
          "sha512": "765329745f56540c039071e8911974645c7cd836a99e8eddf10e53bc02963b5d1931ce13cbbdae3e69ba262655e3aa6b6041d2dd496d7ba9748ea9bf658407ef",
          "sha256": "37d06605af60d3f9c25205049e09cba6eeb3b425d76f81f3d46d8249bf0c9f27",
          "sha1": "319f185172abc87d3d9d35540bfd9f806b417245",
          "md5": "50cf60d4613a59c1572194391689a332"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4-sources.jar",
          "url": "core-xplat-intermediary-2.0.0-alpha.8+1.20.4-sources.jar",
          "size": 223186,
          "sha512": "7d73dfc84951af1daefb389caf9489ae17d88a2b2d54d514145573c702a8147f9c991f693329803feda16e234bd84cb51b4c4b04ae72eb4d58b371f9feb6156e",
          "sha256": "67624e8bfbfe72774b6e6930ba258966f164f29e47f09ebbbbda9a623784f455",
          "sha1": "4f4b257a570fa1eee6f988ba0c28fcfefb09659b",
          "md5": "8a9ec04dfbc3e4b1ef580d399ac4b400"
        }
      ]
    }
  ]
}
