{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "jar-it",
    "version": "0.1.2+1.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-it-0.1.2+1.19.2.jar",
          "url": "jar-it-0.1.2+1.19.2.jar",
          "size": 249997,
          "sha512": "614527c31a5beaaf6855421d61b7fd0151a4e7fae33271b66d874f39b929333243d90844e962d69601d4623ea6665aa8e5352df533399d71f0686021c6fc6ee9",
          "sha256": "a6842e542287e5e92c36728265b995c709561a9577b5e3fb1ee105a3cbf880f4",
          "sha1": "014b3f6b2a17f99dc2c5d91046e399176264e86e",
          "md5": "a7674512d7c3a3e8ca97cc5a52eae8fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core-jvm",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.18.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime-jvm",
          "version": {
            "requires": "0.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.quiltmc.quilt-kotlin-libraries",
          "module": "quilt-kotlin-libraries",
          "version": {
            "requires": "0.1.3+kt.1.7.10+flk.1.8.2-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.7.1-pre.0.3+kneelawk"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "fabric-loader"
            },
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jar-it-0.1.2+1.19.2.jar",
          "url": "jar-it-0.1.2+1.19.2.jar",
          "size": 249997,
          "sha512": "614527c31a5beaaf6855421d61b7fd0151a4e7fae33271b66d874f39b929333243d90844e962d69601d4623ea6665aa8e5352df533399d71f0686021c6fc6ee9",
          "sha256": "a6842e542287e5e92c36728265b995c709561a9577b5e3fb1ee105a3cbf880f4",
          "sha1": "014b3f6b2a17f99dc2c5d91046e399176264e86e",
          "md5": "a7674512d7c3a3e8ca97cc5a52eae8fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-it-0.1.2+1.19.2-sources.jar",
          "url": "jar-it-0.1.2+1.19.2-sources.jar",
          "size": 36262,
          "sha512": "0633addf1bd4c6ce48d4a5b0776074b14ebf337ad560e55e23831bdaa4326f992c93e0fdff6729037fe30cd9e4256be1ebd5968d4ebe2e46ed0e8ca34526d306",
          "sha256": "6a89d6886b254f09678c89300cd4da30439aef58f797bfd83efe2ebf5982260c",
          "sha1": "ebcf84cd84afd290faafe67a95cd476a87926d07",
          "md5": "dc9740f3a418b721a195acf91b141585"
        }
      ]
    }
  ]
}
