{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "0.5.2+1.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-0.5.2+1.19.4.jar",
          "url": "graphlib-0.5.2+1.19.4.jar",
          "size": 225654,
          "sha512": "5748277cffa010272ce1b3454a42d716f5b83ca721b24f8408d0a5367c84bffb553a653d3a70b67818719882e2b0afd6b80c4f85f96f650717f02e9c240420fc",
          "sha256": "cb607dfcdf5bf9f4ba2a883e56c61176ab832ce5970757b94f85b91c497126b9",
          "sha1": "5c2772a103bd94ed5a901b34a076ee4bcda33164",
          "md5": "551221a8e2b636e1bd7208d629c36f2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.5.2+1.19.4.jar",
          "url": "graphlib-0.5.2+1.19.4.jar",
          "size": 225654,
          "sha512": "5748277cffa010272ce1b3454a42d716f5b83ca721b24f8408d0a5367c84bffb553a653d3a70b67818719882e2b0afd6b80c4f85f96f650717f02e9c240420fc",
          "sha256": "cb607dfcdf5bf9f4ba2a883e56c61176ab832ce5970757b94f85b91c497126b9",
          "sha1": "5c2772a103bd94ed5a901b34a076ee4bcda33164",
          "md5": "551221a8e2b636e1bd7208d629c36f2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.5.2+1.19.4-sources.jar",
          "url": "graphlib-0.5.2+1.19.4-sources.jar",
          "size": 162249,
          "sha512": "1d1a0316448b2ccf8df184a5d1f332b9d150ddc721422fd0f1dd9d4790590d9d6985e56721e421a12f461be9a2f9c7ba7cb6b3b89995d08a2e24fa0c10a7f631",
          "sha256": "6b7ae901b0c691ba1b2ea682c13a1e2a93c8114193b921bc015ad25da8aa2859",
          "sha1": "3b1f9e57ca3bb7ef75c0ee3e2c3506b610eff7af",
          "md5": "6b091997ef284c317c4b7173de2d5c49"
        }
      ]
    }
  ]
}
