{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.28+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.28+1.20.jar",
          "url": "graphlib-1.0.0-alpha.28+1.20.jar",
          "size": 301862,
          "sha512": "85c5054f428220cee9d7c0e8149330e5555b917d21a542f1df0df30f642135190cc81e2aa3ae84c6f21f16c4df6fc88df31756f17f6dada15ec222005452bac0",
          "sha256": "50b39b835efb6ab400dc911436d3c205f0c4cc1e173b88779c7fedcd887be9f8",
          "sha1": "7f9041adf62748637a562d0bb44394326a4d14f1",
          "md5": "aa49ced72f4a29966ab25dbc01f82f14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.28+1.20.jar",
          "url": "graphlib-1.0.0-alpha.28+1.20.jar",
          "size": 301862,
          "sha512": "85c5054f428220cee9d7c0e8149330e5555b917d21a542f1df0df30f642135190cc81e2aa3ae84c6f21f16c4df6fc88df31756f17f6dada15ec222005452bac0",
          "sha256": "50b39b835efb6ab400dc911436d3c205f0c4cc1e173b88779c7fedcd887be9f8",
          "sha1": "7f9041adf62748637a562d0bb44394326a4d14f1",
          "md5": "aa49ced72f4a29966ab25dbc01f82f14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.28+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.28+1.20-javadoc.jar",
          "size": 380376,
          "sha512": "b7df1230d2c7787002fd0b4344b92986212b6a2f39558cc7dfaf2aed6a91a76e815842056bdf1080f26971d74e4a04cedd58c43f9ebe85dd97a349b6ff934879",
          "sha256": "0a1dec39ae2bc389baf567be658a642e2695aabb2d1ff30ff80e9092cc7a2a23",
          "sha1": "0b24c7f543fb80439308e1f46c8e4da12154299a",
          "md5": "18180bd0dc7c5c356077a244b7e89b48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.28+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.28+1.20-sources.jar",
          "size": 216679,
          "sha512": "f9a534cc3d82ff1b534bca246946b9ef316d7cc621190c1928fcfd4233fd3a89fcedb0e8cdc13479a198a81361ae8859d84da3711b4f782f69b98eb901f87bdf",
          "sha256": "3811ead31507e0a5de3328af9519e6dc602a3e79aaf92c09445cd686b9193845",
          "sha1": "2b4b75d82fe1f8956d4c278dda515b60c038036a",
          "md5": "bd67adc70ce884517bb8aa00573f8338"
        }
      ]
    }
  ]
}
