{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "extra-mod-integrations",
    "version": "0.4.1+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.0.19+1.20.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "emi-fabric",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "extra-mod-integrations-0.4.1+1.20.1.jar",
          "url": "extra-mod-integrations-0.4.1+1.20.1.jar",
          "size": 156473,
          "sha512": "14ac6450c4f0bf5280c85ac939c510c111e85532acb23c355bea2130a7f937f86f0fd9207c0ffc40c5082776a29533a7fbef3c1e4f46d3c055c464dc61223372",
          "sha256": "85096623105671deb3cf9af84cdea5fa2e4eeb0156b8502ab2f39dde18292330",
          "sha1": "b52e8070940c96a156ba04d377b40f3555049ba7",
          "md5": "f86d7ddb09b01c67f78aa86e8cd3b784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.0.19+1.20.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "emi-fabric",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.0.19+1.20.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "extra-mod-integrations-0.4.1+1.20.1.jar",
          "url": "extra-mod-integrations-0.4.1+1.20.1.jar",
          "size": 156473,
          "sha512": "14ac6450c4f0bf5280c85ac939c510c111e85532acb23c355bea2130a7f937f86f0fd9207c0ffc40c5082776a29533a7fbef3c1e4f46d3c055c464dc61223372",
          "sha256": "85096623105671deb3cf9af84cdea5fa2e4eeb0156b8502ab2f39dde18292330",
          "sha1": "b52e8070940c96a156ba04d377b40f3555049ba7",
          "md5": "f86d7ddb09b01c67f78aa86e8cd3b784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extra-mod-integrations-0.4.1+1.20.1-sources.jar",
          "url": "extra-mod-integrations-0.4.1+1.20.1-sources.jar",
          "size": 91621,
          "sha512": "ed3133668fa9fdf98db09d1102c5d8d227d06274a784ab46cd66fd3d3e3d715455f57bc8171ca30379d5cd2a47da95cdedd29e2b50f99a3c7de6aaf670ea15a9",
          "sha256": "415f111ff70398c938766bbf6c3efca0628d7de9b6e714a583ffc0b408d14d1c",
          "sha1": "0ee72c23daf904985154cb30f8ac85bb2cbf3507",
          "md5": "2a25f50fc5ca09ba89b32850b9715613"
        }
      ]
    }
  ]
}
