{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk.graphlib",
    "module": "syncing-core-xplat-intermediary",
    "version": "2.0.0-alpha.11+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4.jar",
          "size": 47123,
          "sha512": "76b8709f54f633831dd64d4b54ccb96a41c4051c3dd7e6429aa225d7394f42b16288070342a4e7d251b9bce29f227081449126bab969ac201ede1fb99c154ef3",
          "sha256": "a338a6543ea7606a82fd423c32109180d979eaac3e54da639f036e9b90c36ad9",
          "sha1": "0b2ab57a08e07a0de7ff94e631ded1fcfbfe0aa0",
          "md5": "355acd7355c2914663d8a69b8370a3fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4.jar",
          "size": 47123,
          "sha512": "76b8709f54f633831dd64d4b54ccb96a41c4051c3dd7e6429aa225d7394f42b16288070342a4e7d251b9bce29f227081449126bab969ac201ede1fb99c154ef3",
          "sha256": "a338a6543ea7606a82fd423c32109180d979eaac3e54da639f036e9b90c36ad9",
          "sha1": "0b2ab57a08e07a0de7ff94e631ded1fcfbfe0aa0",
          "md5": "355acd7355c2914663d8a69b8370a3fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4-javadoc.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4-javadoc.jar",
          "size": 100065,
          "sha512": "7d1bb770b39643917476686917444af6f7d3027ab3685f45ff515a848ca44462a2c20a09cd36f0339c820923f0a72682ebe1ae21bff0c56d60943db587a758a9",
          "sha256": "2807ebc4396f220b681a3655b46048d0452e76534ad232ba9f8cac4a4f719baa",
          "sha1": "b405179fb692de0263e754023cf89deec7ab3718",
          "md5": "272167cf7f7505015fcbb782189f15a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4-sources.jar",
          "url": "syncing-core-xplat-intermediary-2.0.0-alpha.11+1.20.4-sources.jar",
          "size": 42060,
          "sha512": "5e13d61454cca864eacd1780ebefc1a61c3340e4bfae703a13da41e6cbeb3cdca9309bb7e99ee9336043dce9a5077fff37dcdf940ab66ec055da0ba136156ae4",
          "sha256": "3939bc17ddafd2ac2feadbf3193a999638baac2b29b24fff9ec1d5813c6d46d4",
          "sha1": "75f6ea48fa9f27404dc4645d51081fa3b7970b8f",
          "md5": "a84af3495e31f25dede2eb9b3fcde942"
        }
      ]
    }
  ]
}
