{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "extra-mod-integrations",
    "version": "0.4.2+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.0.29+1.20.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "emi-fabric",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "extra-mod-integrations-0.4.2+1.20.1.jar",
          "url": "extra-mod-integrations-0.4.2+1.20.1.jar",
          "size": 167199,
          "sha512": "3e94b12dd12e2404ceaf61a258e138c436b1e9d2a127a37e7deeabf51a5b0b29292e2d8cfae6c72fffa350b194b35b2bc89c9ea685cb924fcbddd47dc5614495",
          "sha256": "659e32afd34ea60c22cb80013a68e77c1cfc21b51aa71d7ca09a6dd1d841abe2",
          "sha1": "14ed2f2fa2c72ae6fda9a1b744802f655b83de1c",
          "md5": "0e1f5fbe71f642150b5ff2abf3e294cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.0.29+1.20.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "emi-fabric",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.0.29+1.20.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "extra-mod-integrations-0.4.2+1.20.1.jar",
          "url": "extra-mod-integrations-0.4.2+1.20.1.jar",
          "size": 167199,
          "sha512": "3e94b12dd12e2404ceaf61a258e138c436b1e9d2a127a37e7deeabf51a5b0b29292e2d8cfae6c72fffa350b194b35b2bc89c9ea685cb924fcbddd47dc5614495",
          "sha256": "659e32afd34ea60c22cb80013a68e77c1cfc21b51aa71d7ca09a6dd1d841abe2",
          "sha1": "14ed2f2fa2c72ae6fda9a1b744802f655b83de1c",
          "md5": "0e1f5fbe71f642150b5ff2abf3e294cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extra-mod-integrations-0.4.2+1.20.1-sources.jar",
          "url": "extra-mod-integrations-0.4.2+1.20.1-sources.jar",
          "size": 98882,
          "sha512": "5d8180431710f4494edf81c17f1bdb5bceb4479cc250e7a4ae0f6587165df83bc7d2668374302de3790a402da85785bdcdfd24fd6b7f88e871bee3f40597e60a",
          "sha256": "bfd31c5523da46c0f97f14df521476fd174e26d45ca363b44aa6956dd38a7573",
          "sha1": "548f91084a6c293f4a7f1683e78479a92b5db6f7",
          "md5": "cbadaf0bc40bf3a6893c5ddcec849a30"
        }
      ]
    }
  ]
}
