{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "0.4.0+1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-0.4.0+1.19.3.jar",
          "url": "graphlib-0.4.0+1.19.3.jar",
          "size": 80861,
          "sha512": "d0dcd8bc7932da46b1091eb13cb75fee11a9ceda88e1f491291f386c440ad0318299027f76c5369eca31ac0051b83482e0212296402318e62bac8e47fc8ace32",
          "sha256": "6ac12bd3d71e8b1a8b48b2f241de7d505d6e4f7ccda4b3df26d25774076e8c9f",
          "sha1": "f101744a4aaf50b36cae96d017fd85caaed43265",
          "md5": "0cd1511149c1acedddb25ea14e84cfad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.4.0+1.19.3.jar",
          "url": "graphlib-0.4.0+1.19.3.jar",
          "size": 80861,
          "sha512": "d0dcd8bc7932da46b1091eb13cb75fee11a9ceda88e1f491291f386c440ad0318299027f76c5369eca31ac0051b83482e0212296402318e62bac8e47fc8ace32",
          "sha256": "6ac12bd3d71e8b1a8b48b2f241de7d505d6e4f7ccda4b3df26d25774076e8c9f",
          "sha1": "f101744a4aaf50b36cae96d017fd85caaed43265",
          "md5": "0cd1511149c1acedddb25ea14e84cfad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-0.4.0+1.19.3-sources.jar",
          "url": "graphlib-0.4.0+1.19.3-sources.jar",
          "size": 47650,
          "sha512": "17b67f3e4e7614c09d172e8e885fb9be2569c6213e14217c9f46833153d146efd2e9f5c95fbb97a185fab108d8cf8b5881d6da1823e737c6a44fe636cda5427d",
          "sha256": "c58482e59f7814f3d8274cb2b0ad847f289a7d1c25d04874ebebba50f728947e",
          "sha1": "d66747b3313e4d295eed976289c7d789f56c5c56",
          "md5": "ac41ebfa364e75394ec2ec0e758b9759"
        }
      ]
    }
  ]
}
