{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.38+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.10.0-pre.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "net.fabricmd.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.38+1.20.jar",
          "url": "graphlib-1.0.0-alpha.38+1.20.jar",
          "size": 540535,
          "sha512": "1cf4c4a83970a81d9031ec5ddfef6f1fe3049bb03fdf61fcd2d4c478a810a89840f25960d63324624d73bcb820290e3d9520eb338a36a566e7313522c56bee45",
          "sha256": "f5469d5dbbff5bd494e5df8cf9502e7f1340b92eca00f7c98dbe5073610153b0",
          "sha1": "1563a40f4c5b39f96bbad9fdd9645203c0392617",
          "md5": "ae4a8542d505f968412fc80189d16120"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "alexiil.mc.lib",
          "module": "libnetworkstack-base",
          "version": {
            "requires": "0.10.0-pre.2"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "net.fabricmd.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.38+1.20.jar",
          "url": "graphlib-1.0.0-alpha.38+1.20.jar",
          "size": 540535,
          "sha512": "1cf4c4a83970a81d9031ec5ddfef6f1fe3049bb03fdf61fcd2d4c478a810a89840f25960d63324624d73bcb820290e3d9520eb338a36a566e7313522c56bee45",
          "sha256": "f5469d5dbbff5bd494e5df8cf9502e7f1340b92eca00f7c98dbe5073610153b0",
          "sha1": "1563a40f4c5b39f96bbad9fdd9645203c0392617",
          "md5": "ae4a8542d505f968412fc80189d16120"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.38+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.38+1.20-javadoc.jar",
          "size": 439756,
          "sha512": "eaba033171d018b86072a9c794dbd8083f12d74f475b69cbdd836ebe504d4145dc2ef14761bf517397fbcd67807038e2660bb50f9bb78f7d069f6d0c3a858f87",
          "sha256": "27f583cfe739725945bb7293828f376166e895e9c8264a2f865fd5ce16a68edd",
          "sha1": "3e5d16650964902fb8da7f93d3048eb0ca6f05c0",
          "md5": "ae98b147b4d6df7632e6b04f756a6ea3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.38+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.38+1.20-sources.jar",
          "size": 282042,
          "sha512": "99458c3065a24f9578ee78a0c0a3a428cab11f275938d437954b369743b5b1fb90b336cb95c060996dfc8ac587f4ce329bb737a0bca202def837fc7f2663264f",
          "sha256": "e7f03e15eca1687bd104ed4c1af1ac5ce7444c1fff0eb20bd90497399c924358",
          "sha1": "c362baad9e1086cb00a078748991ce8b1ec3f5e4",
          "md5": "9414f000bad1bbf54ab5b7fd71ebfc26"
        }
      ]
    }
  ]
}
