{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.13+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.13+1.20.jar",
          "url": "graphlib-1.0.0-alpha.13+1.20.jar",
          "size": 278963,
          "sha512": "c03bb494baf4dc613b5cb5d6483b6a63f5ef80c5244bda7365283f0f432cccbfa603c90d7958a03c8d42ee39588adb006712491a9db51ef4f9973af8ae5084af",
          "sha256": "d600e7e0bb8f8eed869c0b357916228a234b362eec42b9dda48c46ec8ab8b368",
          "sha1": "8d17ae022a0e0ca8599a6afe1ea91eb762ea7d8b",
          "md5": "5e5e7d0146a5c0eacb95768b079570fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.13+1.20.jar",
          "url": "graphlib-1.0.0-alpha.13+1.20.jar",
          "size": 278963,
          "sha512": "c03bb494baf4dc613b5cb5d6483b6a63f5ef80c5244bda7365283f0f432cccbfa603c90d7958a03c8d42ee39588adb006712491a9db51ef4f9973af8ae5084af",
          "sha256": "d600e7e0bb8f8eed869c0b357916228a234b362eec42b9dda48c46ec8ab8b368",
          "sha1": "8d17ae022a0e0ca8599a6afe1ea91eb762ea7d8b",
          "md5": "5e5e7d0146a5c0eacb95768b079570fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.13+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.13+1.20-javadoc.jar",
          "size": 331447,
          "sha512": "a0ee4d9f8821daa399aab45a00bd8713ead10438196d9ca89292e9e8d27231230b295594f243cdd505b7c37c57f736002b6698b0c2f5c3c2226bb2b625aa0fc5",
          "sha256": "6932e2226f139514f8bd0bbba97bf147294b9e55a3247e2cb08df38a5cc4258a",
          "sha1": "befe1db94a4ac1db076dce5ee325850b429b2eb6",
          "md5": "57c27852595c880c9678caf930a9f208"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.13+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.13+1.20-sources.jar",
          "size": 201003,
          "sha512": "134baf3884a3b03e7c5c960a57888a84c8783ccc7fb2be0c520454fa60f93da74ed9fffaf2994db2ef85ec3e5f506e5ea328c5da9369007239cd24423d58dbd0",
          "sha256": "dffd84a46a1f5c134c96b31f3ddc092ba013d6508e43804a8110a377ae6c682f",
          "sha1": "d858e9504ba52e8a9379e9b2b026b271ace76802",
          "md5": "bb9e4dc166cc0cf1ee8caf0a56cf842b"
        }
      ]
    }
  ]
}
