{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.22+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.22+1.20.jar",
          "url": "graphlib-1.0.0-alpha.22+1.20.jar",
          "size": 282683,
          "sha512": "9cf5cced52f821004ecf30fde6619bdbaec3e1aecc8431309c4a082278adf51015e2c4cce6cfb402fef65fde2a008616a06958e253a7cfdb9af44a2cc18b9dc3",
          "sha256": "0dc02682dafe230f67ba8748d9788d1c89f8f4f9a6168a1ce4ad66236a0b92ff",
          "sha1": "1be91ddc56b5ecce023568861732597a8a5e5182",
          "md5": "d536de783110e7db1e546aaafa166cb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.22+1.20.jar",
          "url": "graphlib-1.0.0-alpha.22+1.20.jar",
          "size": 282683,
          "sha512": "9cf5cced52f821004ecf30fde6619bdbaec3e1aecc8431309c4a082278adf51015e2c4cce6cfb402fef65fde2a008616a06958e253a7cfdb9af44a2cc18b9dc3",
          "sha256": "0dc02682dafe230f67ba8748d9788d1c89f8f4f9a6168a1ce4ad66236a0b92ff",
          "sha1": "1be91ddc56b5ecce023568861732597a8a5e5182",
          "md5": "d536de783110e7db1e546aaafa166cb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.22+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.22+1.20-javadoc.jar",
          "size": 337615,
          "sha512": "fadb42fecb6fe683e58b46210f65811b9673e0e7600620b764a480305c83ac0f5b5089b06a8c6a2c88784686341aec41e1ad9d4c0838aee92cd8d212acfd6b17",
          "sha256": "4a63b551e6f9d1d48c54584f9d09520f762b9d0076266c92536e0bb53e80f3c4",
          "sha1": "b6a76956c3339b7f647ae2818cbc0c78c554e696",
          "md5": "2d68361a8e8846c249be8bc70810e3a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.22+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.22+1.20-sources.jar",
          "size": 203340,
          "sha512": "55a22fd60c8b09b40e7b0577aa87efe66b8708b9f70b78e15f1ad7b8e11fce902c95a77b229f62571a60be6e035db45cdcc9b04b967d18340271d40d709dc5bd",
          "sha256": "38f9cfe0e7b71e576cf882f697bdc05acb63b6a22dde46a7168701588a955d09",
          "sha1": "e20574e2386a1feb621733267a348f6dd382b1b2",
          "md5": "e88e79600a17003449482adc0890a6f0"
        }
      ]
    }
  ]
}
