# This handles publishing of the kneelawk-com binary

name: publish-bin

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Build Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Server Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Make Sure SSH Dir Exists
        run: |
          mkdir -p ~/.ssh/
      - name: Grab SSH Key
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_ORACLE_MAIN_WEBSITE }}
      - name: Add Known Hosts
        run: |
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS_ORACLE_MAIN_WEBSITE }}
      - name: Stop Running Server
        run: |
          ssh opc@146.235.207.79 'sudo docker compose down'
      - name: Upload New Binary
        run: |
          rsync -v target/release/kneelawk-com opc@146.235.207.79:kneelawk-com/kneelawk-com
      - name: Start Server
        run: |
          ssh opc@146.235.207.79 'sudo docker compose up --wait --wait-timeout 10'
