{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "kmodlib-overlay",
    "version": "0.2.2+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.2+1.20.jar",
          "url": "kmodlib-overlay-0.2.2+1.20.jar",
          "size": 15701,
          "sha512": "39946fa1d4f27876f1d855feefe336bef7f83eb2da6d6c5c79c882e671603736b3aef787c7110a7f9a499db5ee41efaf10a1d8ea6bff32f1d95b2db0ae80307c",
          "sha256": "1f8fdccff6880e064f04fe86b24223ac284819911cd11b0d55cd917ecd3f389b",
          "sha1": "349b22147c85a8365dd67d8aef7c9ac5503407b8",
          "md5": "260ef19320b1690a8f5e6dfd80d00c83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.2+1.20.jar",
          "url": "kmodlib-overlay-0.2.2+1.20.jar",
          "size": 15701,
          "sha512": "39946fa1d4f27876f1d855feefe336bef7f83eb2da6d6c5c79c882e671603736b3aef787c7110a7f9a499db5ee41efaf10a1d8ea6bff32f1d95b2db0ae80307c",
          "sha256": "1f8fdccff6880e064f04fe86b24223ac284819911cd11b0d55cd917ecd3f389b",
          "sha1": "349b22147c85a8365dd67d8aef7c9ac5503407b8",
          "md5": "260ef19320b1690a8f5e6dfd80d00c83"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.2+1.20-javadoc.jar",
          "url": "kmodlib-overlay-0.2.2+1.20-javadoc.jar",
          "size": 85459,
          "sha512": "f15e2bd94b3aee29b0f4cceb671266031c1da9e0ccdad7f1b5bd596e287e2250ba9baa736c6e03f111253322945515ca767da1530615f86d7af80a69ebab5e1d",
          "sha256": "3bf45ba11780e42f86be6769432f6c8efd1d402308c6f9e6241fb3f2aef13217",
          "sha1": "4535d013241f4437adc66b8fd55c1b0a253997b0",
          "md5": "69410a5b3c5c8ef33d927ac2bd772898"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kmodlib-overlay-0.2.2+1.20-sources.jar",
          "url": "kmodlib-overlay-0.2.2+1.20-sources.jar",
          "size": 12899,
          "sha512": "760048ee3dde0a6727a848fa7a940b553287c1f3c757fc82ac85293b5a57d0d145a2a902eed42ac3b06f95f03302e73a38925e36f8e0b97d80b9dff8c0e19dc7",
          "sha256": "99d5b949d32457ae4ee7a7e29b77e93cb5f233732a82ad04141c9fb7b6cc86c6",
          "sha1": "ab5b0258e42139114f52c13f0423aef5dc631dbd",
          "md5": "1db4f86cadbe6389584820eda9cf3f2d"
        }
      ]
    }
  ]
}
