{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kneelawk",
    "module": "graphlib",
    "version": "1.0.0-alpha.9+1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.9+1.20.jar",
          "url": "graphlib-1.0.0-alpha.9+1.20.jar",
          "size": 256455,
          "sha512": "709f76a38c649e8b7059a4db3dd662caba77d3595bb9bdd3637c2824176e896c837f480541d4139d0b733f63c3a797efb400c102489fd8c861e3916218c30a67",
          "sha256": "7e09ee6143fa1e966e1006aff78aa398e5a7acff99e00c53fc62585db430cbc2",
          "sha1": "5ad0938733312dc01c70572b09a14c4b9bcff1b1",
          "md5": "651b527eaa7d27acb01266ff3265c4d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.9+1.20.jar",
          "url": "graphlib-1.0.0-alpha.9+1.20.jar",
          "size": 256455,
          "sha512": "709f76a38c649e8b7059a4db3dd662caba77d3595bb9bdd3637c2824176e896c837f480541d4139d0b733f63c3a797efb400c102489fd8c861e3916218c30a67",
          "sha256": "7e09ee6143fa1e966e1006aff78aa398e5a7acff99e00c53fc62585db430cbc2",
          "sha1": "5ad0938733312dc01c70572b09a14c4b9bcff1b1",
          "md5": "651b527eaa7d27acb01266ff3265c4d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.9+1.20-javadoc.jar",
          "url": "graphlib-1.0.0-alpha.9+1.20-javadoc.jar",
          "size": 291504,
          "sha512": "ce3e47996d26c72d3a81b3303204d12d5b4fd5bef819f25b6215432123021a8944108050b724077a07b22cfd14c4f8855ba4240d68d553dbf1506c4c0f5ea874",
          "sha256": "4960dce76e2185731df087939769e56fd8c61828395101a993da2592afa936d6",
          "sha1": "fa915d85f01d6365d31995d6cd124c8f88819ef5",
          "md5": "a17e783f2535cc6821067601b8b33598"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphlib-1.0.0-alpha.9+1.20-sources.jar",
          "url": "graphlib-1.0.0-alpha.9+1.20-sources.jar",
          "size": 188095,
          "sha512": "5d3485de5bc36960356a07cddff89e715b57c98b7b3cd5a9e5f0016168efca41991e918de1cc52ac8a404afce3cafa9924e6507d419fcf1b5b9add9eb78d914e",
          "sha256": "9400545095ec894ffa5e9bf14e47d9341d5e59d7da9f901447b1a1d5c669c747",
          "sha1": "427604928509ad3db5b3572b6ae0a794b8acbf4d",
          "md5": "5c58befdd083e3f8c9947fbfe6fd197a"
        }
      ]
    }
  ]
}
